scality/cloudserver

tests/unit/api/objectACLauth.js, tests/unit/api/objectGet.js, tests/unit/api/objectGetACL.js, tests/unit/bucket/bucket_mem_api.js
Remove some warnings in unit tests files
=> [Lint](clean): Remove some warnings

tests/unit/DummyRequest.js, tests/unit/api/bucketGet.js, tests/unit/api/bucketGetACL.js, tests/unit/api/listMultipartUploads.js, tests/unit/api/multipartUpload.js
- Remove some warnings in unit tests files
=> [Lint](clean): Remove some warnings (2)

lib/api/apiUtils/bucket/bucketDeletion.js, lib/api/bucketPutACL.js, lib/api/completeMultipartUpload.js, lib/api/initiateMultipartUpload.js, lib/api/listMultipartUploads.js, lib/api/multipartDelete.js, lib/api/objectDelete.js, lib/api/objectGetACL.js, lib/api/objectHead.js, lib/api/objectPutACL.js, lib/api/objectPutPart.js
- Remove some warnings in lib/api files
=> [Lint](clean): Remove some warnings (3)

lib/Config.js, lib/data/wrapper.js, lib/metadata/wrapper.js, lib/server.js
By default S3 will be using file backend. Other valid backends are
file and scality
=> FT: set file backend as the default backend

lib/api/bucketGet.js, lib/api/listParts.js, lib/utilities/escapeForXML.js, tests/functional/aws-node-sdk/test/bucket/get.js, tests/functional/aws-node-sdk/test/legacy/tests.js, tests/unit/api/bucketGet.js
=> BF: escape characters to generate valid xml

lib/api/api.js
- Send the data object for arsenal
=> [Auth](ft): Use data object

lib/api/bucketGet.js, tests/functional/aws-node-sdk/test/bucket/get.js
Quotes should surround the etag in a bucket listing.
=> Add quotes to etag in bucket listing

lib/Config.js
=> FT: S3METADATA env

Dockerfile
Rebased pr https://github.com/scality/S3/pull/115
=> Fix Dockerfile, provide absolute paths for volumes

lib/api/completeMultipartUpload.js, lib/api/objectPut.js, lib/services.js, tests/functional/aws-node-sdk/test/object/objectOverwrite.js
=> Only new metadata stored when obj put overwrite

tests/functional/aws-node-sdk/test/object/objectOverwrite.js
This test is not working properly, because the
promise is not return to mocha.
This Pull request fix that
Fixes https://github.com/scality/S3/issues/131
=> FIX: Object overwrite test

lib/api/objectPut.js
This closes https://github.com/scality/S3/issues/129
=> Encrypt data on put when bucket is transient

lib/auth/in_memory/checker.js, lib/data/file/backend.js, lib/utilities/logger.js
http://ci.ironmann.io/gh/scality/Integration/2367#build-parameters end to end passed without a hitch.
=> refactor(werelogs): use new API

circle.yml, lib/kms/utilities.js, tests/functional/s3cmd/tests.js
- Create encryption bucket in s3cmd functionals tests if
the env variable ENABLE_KMS_ENCRYPTION is set to true
- Update circle.yml to test all cases
=> FT: Functional tests kms 

config.json, lib/Config.js, lib/routes.js, lib/routes/routeDELETE.js, lib/routes/routeGET.js, lib/routes/routePUT.js, lib/utapi.js, package.json, utapiServer.js
- Integrates utapi server that can be launched using npm run start_utapi
for listing time series metrics
- Introduces Utapi client integration with S3 actions
=> FT: Utapi metrics integration

lib/api/completeMultipartUpload.js, tests/functional/aws-node-sdk/test/legacy/tests.js, tests/unit/api/multipartUpload.js
Closes https://github.com/scality/S3/issues/163
=> FIX: Surround ETag with double quotes

package.json
=> BF: Move commander module to be prod. dependency

lib/routes/routeGET.js
Action : listPart does a pushMetricListMultipartUploadParts
=> FIX: listPart -> pushMetricListMultipartUploadParts

lib/routes/routesUtils.js, tests/unit/utils/setPartRanges.js
The setPartRanges function takes an outer range request and applies it to the parts in the data source.  We had some off by one errors which this PR fixes.
Formal review requested, @vrancurel
=> BF: Fix range utility

tests/functional/aws-node-sdk/test/mocha.opts, tests/functional/s3cmd/package.json, tests/functional/s3curl/package.json
=> FIX: #178 change mocha functional tests timeout

tester.js, tests/functional/s3cmd/package.json, tests/functional/s3curl/package.json
In order to increase timeout for our functional tests.
=> Increase timeout for fonctional tests

lib/routes/routePUT.js
=> fix: send resource for object copy push metrics

lib/routes/routePUT.js
This brings much needed fixes that will go along with Integration's forward port.
=> Fwdport 6.2 to master

README.md
We had a lot of issues opened because of hostname configuration.
I think it would be wise to add a section inside our READ.ME
=> Add Configuring section

lib/routes/routePUT.js, tests/functional/aws-node-sdk/test/object/objectCopy.js, tests/functional/aws-node-sdk/test/object/put.js, tests/functional/aws-node-sdk/test/object/putPart.js
=> fix: error response for object level encryption

lib/api/objectPut.js
=> fix: send content length for 0B objects

lib/api/objectPutPart.js, tests/functional/aws-node-sdk/test/object/putPart.js
Fixes https://github.com/scality/S3/issues/239
=> Check for negative part number on put part

lib/api/api.js, lib/api/apiUtils/authorization/aclChecks.js, lib/api/apiUtils/bucket/bucketDeletion.js, lib/api/bucketGetVersioning.js, lib/api/bucketPutVersioning.js, lib/metadata/BucketInfo.js, lib/metadata/wrapper.js, lib/routes/routeGET.js, lib/routes/routePUT.js, lib/services.js, tests/functional/aws-node-sdk/test/bucket/testBucketVersioning.js, tests/unit/api/bucketDelete.js, tests/unit/api/bucketPut.js, tests/unit/api/deletedFlagBucket.js, tests/unit/api/transientBucket.js, tests/unit/bucket/BucketInfo.js, tests/unit/bucket/bucket_mem_api.js
Step 1 (this PR): S3 to support versioning for buckets.
Step 2: S3 to provide routes for interacting with Metadata.
Step 3: S3 to provide versioning support for each operation.
Step 4: MetaData to support versioning.
=> bucket versioning #1 : prerequisites

lib/metadata/acl.js, lib/metadata/bucketclient/backend.js, lib/metadata/wrapper.js
Step 1: S3 to support versioning for buckets.
Step 2 (this PR): S3 to provide routes for interacting with Metadata.
Step 3: S3 to provide versioning support for each operation.
Step 4: MetaData to support versioning.
=> bucket versioning #2 : versioning path to MetaData

lib/routes.js, tests/functional/healthchecks/master.json, tests/functional/healthchecks/test/checkRoutes.js, tests/unit/healthchecks/healthcheckResponse.js
This introduces routes for simple healthchecks that will be implemented
=> Make routes for healthcheck with tests

tests/functional/healthchecks/test/checkRoutes.js
Will be re-enabled as soon as the tests are updated.
=> Temporarily skip healthcheck tests

tests/functional/aws-node-sdk/test/bucket/testBucketStress.js
It's a functional test to check if the behavior of metadata is correct in the case of recycling buckets.
To verify to some extend https://github.com/scality/MetaData/issues/707.
=> stress test for bucket creation/deletion

tests/functional/healthchecks/test/checkRoutes.js
This commit is to fix the e2e failure that came up yesterday post merge
=> Fix for end-to-end failure

lib/api/completeMultipartUpload.js, lib/api/initiateMultipartUpload.js, lib/api/listMultipartUploads.js
* Fix #290
* Fix #291 
* Fix #292
=> CLEANUP: Remove xml module dependency in MPU APIs

tests/functional/aws-node-sdk/test/object/getRange.js
=> CLEANUP: Add range tests with large end position

tests/functional/s3curl/tests.js
Until we figure out how to parse the response in the CI
=> Skip test header mismatched MD5

lib/utils.js, tests/functional/aws-node-sdk/test/bucket/get.js
FIXES #294 
Keys and values are already decoded with .query
https://nodejs.org/api/url.html#url_urlobject_query
=> COMPAT:listing objects with percentage delimiter

lib/routes.js, tests/functional/aws-node-sdk/test/bucket/put.js, tests/functional/aws-node-sdk/test/object/get.js
=> COMPAT: create bucket with empty name

lib/metadata/bucketfile/backend.js, tests/functional/aws-node-sdk/test/object/get.js
Fixes https://github.com/scality/S3/issues/342
=> BF: File backend error should be NoSuchKey

config.json
=> Add default endpoint "s3.scality.test"

lib/api/listParts.js, tests/functional/aws-node-sdk/test/legacy/tests.js, tests/unit/api/listParts.js
=> COMPAT: listParts returns <ETag> section with quote

lib/api/apiUtils/bucket/bucketCreation.js
=> create bucket keys after checking bucket existence

lib/api/apiUtils/bucket/bucketDeletion.js, lib/kms/file/backend.js, lib/kms/in_memory/backend.js, lib/kms/wrapper.js
=> make usage of kms.destroyBucketKey on bucket deletion

lib/api/completeMultipartUpload.js, tests/unit/api/multipartUpload.js
=> COMPAT: return InvalidPart if complete MPU with missing part

lib/api/objectCopy.js, tests/functional/aws-node-sdk/test/object/objectCopy.js
=> COMPAT: Replace ContentType if copyObject with REPLACE

lib/api/bucketGetVersioning.js, package.json
* Remove the dependency on xml module in bucketGetVersioning api
* Remove the xml module from package.json as it is no longer used
in S3
=> CLEANUP: Remove xml module usage from bucketGetVersioning api

package.json, tests/unit/utils/responseStreamData.js
Update ready-set-stream npm version, and add
non-regression testing.
Fixes https://github.com/scality/S3/issues/334
=> Fix: send back error

lib/api/completeMultipartUpload.js, tests/unit/api/multipartUpload.js
=> COMPAT: Fix incorrect err code for empty MPU

README.md
Make the Readme.md clearer.
Part: Saving the data or metadata in different locations
=> README :saving the data or metadata in different locations

lib/auth/vault.js
Sending logger to Vault, to log error in
request and send back internal error to
S3
Fixes https://github.com/scality/S3/issues/374
=> FIX: Vault returning internal error

tests/functional/aws-node-sdk/test/legacy/authV2QueryTests.js
This PR modifies signature V2 tests for https://github.com/scality/Arsenal/pull/193
=> TEST: modify tests for v2SignExpires

conf/authdata.json, tests/functional/aws-node-sdk/lib/json/mem_credentials.json
=> FIX: access key should not have slash

lib/api/objectCopy.js, lib/api/objectPutCopyPart.js, tests/functional/s3curl/tests.js
=> COMPAT: Date format for object copy and copy part

lib/api/objectPutACL.js, lib/utilities/aclUtils.js, tests/functional/aws-node-sdk/test/object/putObjAcl.js, tests/unit/api/objectPutACL.js, tests/unit/helpers.js
FIXES #367
Hope it's OK I added onto aclUtils.parseAclXml! Open to other suggestions.
=> COMPAT: putObjectACL reject changing owner ID

lib/utapi/utilities.js
=> BF: fix listBucketMetrics

init.js, lib/metadata/bucketclient/backend.js, lib/metadata/bucketfile/backend.js, lib/routes.js
Fixes https://github.com/scality/IronMan-S3/issues/411#event-861971864
=> FIX: Log caught errors properly

tests/functional/aws-node-sdk/test/object/copyPart.js, tests/functional/s3cmd/tests.js
The output parsing was heavily reliant on the order of fields, so a new change in Werelogs
would break the tool. The parsing has been updated to accommodate future changes.
Fix #412
=> fix: parsing for kms tests

lib/api/bucketPut.js, lib/api/bucketPutACL.js, lib/api/objectPut.js, lib/api/objectPutACL.js, lib/utilities/aclUtils.js, tests/unit/api/bucketGetACL.js, tests/unit/api/bucketPut.js, tests/unit/api/bucketPutACL.js, tests/unit/api/objectDelete.js, tests/unit/api/objectGetACL.js, tests/unit/api/objectPut.js, tests/unit/api/objectPutACL.js, tests/unit/helpers.js, tests/unit/utils/aclUtils.js
=> FIX: Check bad acl headers

lib/routes/routesUtils.js
=> FIX: Surround response.setHeader with try/catch

lib/utapi/utapi.js
=> fix: pass healthchecks config to Utapi

lib/api/apiUtils/object/parseRange.js, lib/api/apiUtils/object/setUpCopyLocator.js, lib/api/objectGet.js, tests/functional/aws-node-sdk/test/legacy/tests.js, tests/unit/utils/validateRange.js
=> COMPAT: AWS returns InvalidRange error for getObject

lib/routes/routePUT.js
=> COMPAT: PUT empty content-lenght header

lib/metadata/bucketfile/backend.js
Fixes https://github.com/scality/S3/issues/271
=> FIX: Prevent unlimited setting of event listeners

lib/auth/vault.js, lib/data/wrapper.js, lib/metadata/bucketclient/backend.js, lib/metadata/wrapper.js, lib/utilities/healthcheckHandler.js, tests/unit/api/objectGet.js
Title says it all!
Depends on vaultclient pr #113 https://github.com/scality/vaultclient/pull/113
and bucketclient pr #91 https://github.com/scality/bucketclient/pull/91
=> Add functions to bucket- and vaultclient for deep healthcheck

lib/data/wrapper.js, lib/services.js
=> BF: Fix logging location of delete keys

lib/api/objectPut.js, lib/services.js
=> CLEANUP: Remove `dataStore` from services

lib/api/completeMultipartUpload.js, tests/functional/aws-node-sdk/test/object/completeMPU.js, tests/unit/api/multipartUpload.js
A user should be able to complete an MPU with fewer
parts than were originally put.  The other parts
are just discarded.
=> FIX: Complete MPU allows fewer parts than put

lib/api/api.js, lib/api/apiUtils/bucket/bucketWebsite.js, lib/api/bucketGetWebsite.js, lib/routes/routeGET.js, lib/utilities/pushMetrics.js, tests/functional/aws-node-sdk/test/bucket/getWebsite.js, tests/unit/api/bucketGetWebsite.js, tests/unit/api/deletedFlagBucket.js, tests/unit/api/transientBucket.js
Should return XML of a bucket's website configuration stored in metadata.
Depends on
scality/Arsenal#200,
scality/Arsenal#203
scality/utapi#69,
scality/Integration#365, &
scality/S3#469
=> FT: Add getBucketWebsite to API

lib/routes.js, lib/routes/routesUtils.js
=> Add default contentLength field in log

lib/api/api.js, lib/api/apiUtils/bucket/bucketCors.js, lib/api/bucketPutCors.js, lib/metadata/BucketInfo.js, lib/metadata/ModelVersion.md, lib/routes.js, lib/routes/routePUT.js, tests/functional/aws-node-sdk/test/bucket/putCors.js, tests/functional/s3cmd/tests.js, tests/unit/api/bucketPutCors.js, tests/unit/api/deletedFlagBucket.js, tests/unit/api/transientBucket.js, tests/unit/bucket/BucketInfo.js, tests/unit/helpers.js
Reference: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTcors.html
Depends on scality/Arsenal#211
=> FT: Implement put bucket CORS api

lib/Config.js, lib/api/bucketDelete.js, lib/api/bucketDeleteWebsite.js, lib/api/bucketGet.js, lib/api/bucketGetACL.js, lib/api/bucketGetVersioning.js, lib/api/bucketGetWebsite.js, lib/api/bucketHead.js, lib/api/bucketPut.js, lib/api/bucketPutACL.js, lib/api/bucketPutVersioning.js, lib/api/bucketPutWebsite.js, lib/api/completeMultipartUpload.js, lib/api/initiateMultipartUpload.js, lib/api/listMultipartUploads.js, lib/api/listParts.js, lib/api/multiObjectDelete.js, lib/api/multipartDelete.js, lib/api/objectCopy.js, lib/api/objectDelete.js, lib/api/objectGet.js, lib/api/objectGetACL.js, lib/api/objectHead.js, lib/api/objectPut.js, lib/api/objectPutACL.js, lib/api/objectPutPart.js, lib/utapi/utilities.js
Pushes account-level metrics for any API that includes the `AuthInfo` object.
Depends on https://github.com/scality/utapi/pull/74
=> Add Utapi account-level metrics

circle.yml, lib/api/completeMultipartUpload.js, tests/functional/aws-node-sdk/test/object/bigMpu.js
Adds env variable to allow for putting small parts
in an mpu for testing purposes.
Need to add ENV_NODE=testing env variable for end to end testing.
=> TEST: Test large MPU

lib/api/api.js, lib/api/apiUtils/bucket/bucketCors.js, lib/api/bucketGetCors.js, lib/routes/routeGET.js, tests/functional/aws-node-sdk/test/bucket/getCors.js, tests/functional/s3cmd/tests.js, tests/unit/api/bucketGetCors.js, tests/unit/api/deletedFlagBucket.js, tests/unit/api/transientBucket.js
Depends on scality/S3#497 putBucketCors
& scality/Arsenal#213 , adding NoSuchCORSConfiguration error to Arsenal
Note: will not pass CI until putBucketCors is merged :)
=> FT: Add bucketGetCors to API

lib/utilities/healthcheckHandler.js
=> fix: deep healthcheck on server startup

lib/routes/routeDELETE.js, tests/functional/aws-node-sdk/test/object/abortMPU.js
=> Fix: Check for missing key in delete route

lib/routes/routePUT.js
=> COMPAT: PUT empty content-length header should return BadRequest

lib/server.js
=> ft: log http parser errors

lib/api/api.js, lib/api/bucketDeleteCors.js, lib/routes/routeDELETE.js, tests/functional/aws-node-sdk/test/bucket/deleteCors.js, tests/unit/api/bucketDeleteCors.js, tests/unit/api/deletedFlagBucket.js, tests/unit/api/transientBucket.js
Depends on scality/S3#497 (putBucketCors)
=> FT: Add bucketDeleteCors to API

lib/api/bucketGet.js, tests/functional/aws-node-sdk/test/bucket/get.js
=> fix: escape invalid xml characters

lib/routes/routePUT.js, tests/functional/aws-node-sdk/test/bucket/put.js
=> COMPAT put bucket response should have location header

lib/api/objectGet.js, tests/functional/aws-node-sdk/test/legacy/tests.js
=> COMPAT: get emptyObject with range header

lib/routes/routeDELETE.js, tests/functional/aws-node-sdk/test/bucket/deleteCors.js
More tests coming with Ceph tests in Integration.
=> COMPAT: deleteCORS return 204 status

lib/routes.js, tests/functional/s3curl/tests.js
=> FIX: Check for key for mpu key routes

lib/routes/routePOST.js, lib/routes/routePUT.js, tests/functional/aws-node-sdk/test/bucket/putAcl.js, tests/functional/aws-node-sdk/test/object/compluteMpu.js
Fixes #538 
plus warning over ~~1 MB~~ 512 KB of post body
=> reduce amount of memory allocation and gc stress

lib/routes/routePUT.js, tests/functional/aws-node-sdk/test/object/put.js
(cherry picked from commit b0a8ad79248676f7d03f39d89cc8322dd3413973)
=> FIX: Allow for key called slash

lib/services.js
=> fix: missing error callbacks

lib/server.js
Log worker pid to help worker investigations
Fixes https://github.com/scality/S3/issues/544
=> FIX: Worker pid

lib/routes/routeDELETE.js, tests/functional/aws-node-sdk/test/bucket/deleteWebsite.js
=> COMPAT: Return 204 for bucketDeleteWebsite

tests/functional/aws-node-sdk/test/bucket/getCors.js, tests/functional/aws-node-sdk/test/bucket/putCors.js
Add a few more functional tests regarding validity of case in CORS rules.
=> TEST: Add more cors tests for case values

lib/routes/routePOST.js
=> fix: increase max post body size

lib/routes/routePOST.js
=> fix: explict checks for POST routes

lib/routes/routePOST.js
=> fix: explicit check for invalid multiobject delete

lib/routes/routesUtils.js
FIXES #565 
This change fixes couple s3_website Ceph tests.
These tests are also going to be added in the CI.
=> COMPAT: website - Error HTML response

README.md
AWS-CLI: adding additional information about the configuration.
=> README: add AWS CLI configuration

lib/api/initiateMultipartUpload.js, tests/unit/api/multipartUpload.js
=> FT: log uploadId for initiateMPU

lib/api/multipartDelete.js, tests/functional/aws-node-sdk/test/object/deleteMpu.js, tests/unit/api/deletedFlagBucket.js, tests/unit/api/multipartDelete.js, tests/unit/api/multipartUpload.js, tests/unit/api/transientBucket.js
=> FIX: abortMpu returns 204 if no such uploadId

lib/api/initiateMultipartUpload.js, lib/api/multipartDelete.js, lib/server.js, tests/functional/aws-node-sdk/test/object/deleteMpu.js, tests/unit/api/deletedFlagBucket.js, tests/unit/api/multipartDelete.js, tests/unit/api/multipartUpload.js, tests/unit/api/transientBucket.js
=> Forward ports 6.2.5 to 6.3

lib/api/initiateMultipartUpload.js, lib/api/multipartDelete.js, lib/server.js, lib/utapi/utilities.js, tests/functional/aws-node-sdk/test/object/deleteMpu.js, tests/unit/api/deletedFlagBucket.js, tests/unit/api/multipartDelete.js, tests/unit/api/multipartUpload.js, tests/unit/api/transientBucket.js
Forward port rel/6.3 to rel/6.4
=> Forward port rel/6.3 to rel/6.4

lib/api/multipartDelete.js, tests/functional/aws-node-sdk/test/object/bigMpu.js, tests/functional/aws-node-sdk/test/object/deleteMpu.js, tests/unit/api/deletedFlagBucket.js, tests/unit/api/multipartDelete.js, tests/unit/api/multipartUpload.js, tests/unit/api/transientBucket.js
=> FT: enable usEastBehavior for abortmpu result

lib/api/apiUtils/object/parseRange.js, tests/functional/aws-node-sdk/test/legacy/tests.js
Fix invalid range when start is negative
Fixes https://github.com/scality/S3/issues/592
=> FIX: Invalid range negative start

lib/api/apiUtils/object/parseRange.js, lib/api/multipartDelete.js, tests/functional/aws-node-sdk/test/legacy/tests.js, tests/functional/aws-node-sdk/test/object/bigMpu.js, tests/functional/aws-node-sdk/test/object/deleteMpu.js, tests/unit/api/deletedFlagBucket.js, tests/unit/api/multipartDelete.js, tests/unit/api/multipartUpload.js, tests/unit/api/transientBucket.js
=> Forward rel/6.3 to rel/6.4

lib/api/apiUtils/object/parseRange.js, lib/api/multipartDelete.js, tests/functional/aws-node-sdk/test/legacy/tests.js, tests/functional/aws-node-sdk/test/object/bigMpu.js, tests/functional/aws-node-sdk/test/object/deleteMpu.js, tests/unit/api/deletedFlagBucket.js, tests/unit/api/multipartDelete.js, tests/unit/api/multipartUpload.js, tests/unit/api/transientBucket.js
=> Forward rel/6.4 to master

lib/api/api.js, lib/api/websiteGet.js, lib/api/websiteHead.js, tests/functional/aws-node-sdk/lib/utility/cors-util.js, tests/functional/aws-node-sdk/lib/utility/website-util.js, tests/functional/aws-node-sdk/test/object/corsHeaders.js, tests/functional/aws-node-sdk/test/object/websiteGetWithACL.js, tests/functional/aws-node-sdk/test/object/websiteHeadWithACL.js
=> COMPAT: websiteGet and websiteHead with ACLs

tests/unit/testConfigs/locConstraintAssert.js
Removing `.only` in unit tests.
=> BF: removing .only in unit tests

lib/Config.js, lib/utapi/utapiReplay.js, package.json, utapiReplay.js
* Add npm script to initiate UtapiReplay instance and start the replay job.
* Update Config.js to handle UtapiReplay configuration options.
Depends on https://github.com/scality/utapi/pull/109.
=> FT: Add UtapiReplay

config.json
=> FIX: Request with hostname localhost returns InvalidURI

.babelrc, Dockerfile, DockerfileMem, README.md, circle.yml, lib/server.js, package.json
=> FT: Node v6

init.js
Generates once a unique identifier that will later be used for reporting.
=> Generate a unique identifier on init

lib/services.js, tests/functional/aws-node-sdk/test/service/get.js
=> FIX: Increase bucket listing limit to 10,000

README.md
Signed-off-by: Evgeny Rudinsky <evgeny.rudinsky@gmail.com>
=> CloudBerry Lab FREE

DOCKER.md, docker-entrypoint.sh
Running S3 Docker with SSL using environment variable.
=> dev: Running S3 Docker with SSL

DOCKER.md
=> FIX: updating Docker configuration documentation

README.md, lib/api/apiUtils/object/BackendInfo.js, tests/multipleBackend/objectPut.js, tests/multipleBackend/objectPutCopyPart.js, tests/multipleBackend/objectPutPart.js, tests/unit/multipleBackend/BackendInfo.js
=> BF: default location for non-listed endpoint

lib/utapi/utilities.js
Add options to list user and service level metrics.
=> FT: Add remaining Utapi listing levels

lib/api/bucketPutVersioning.js, tests/functional/aws-node-sdk/test/bucket/testBucketVersioning.js
If MFA Delete–enabled, we return NotImplemented error.
=> bf: versioning - check if MfaDelete is enabled

DOCKER.md, config.json, lib/data/wrapper.js, lib/utilities/healthcheckHandler.js, locationConfig.json, tests/multipleBackend/backendHealthcheckResponse.js, tests/unit/api/multipartDelete.js, tests/unit/bucket/bucketCreation.js
Fixes S3 not returning error on failing healthcheck in any of multiple data backends
=> Fail healthchecks if any on multiple data backends fail

tests/functional/aws-node-sdk/test/versioning/objectCopy.js
1. For object copy, checking that we are conform on deleting data when copying to the same bucket/objectKey and versioning is enabled.
=> TEST: versioning objectCopy add more checks

tests/functional/aws-node-sdk/test/versioning/bucketDelete.js
Testing delete bucket
- if delete marker still bucket
- if version still in bucket
- if no versions or delete marker still in bucket
=> TEST: add more tests for deleteBucket with versioning

lib/api/bucketPut.js, lib/api/multiObjectDelete.js, lib/auth/in_memory/backend.js
This is to add version ids to the request contexts for multi object delete requests.
Dependency of scality/Vault#728
=> ft: add versionId to multiObjDelete requestContext [S3C-184]

tests/functional/aws-node-sdk/test/versioning/objectGet.js
Add more tests for getObject versioning.
=> S3C-184 TEST: add getObject versioning tests

circle.yml, lib/metadata/bucketfile/backend.js, tests/functional/aws-node-sdk/test/object/completeMPU.js, tests/functional/aws-node-sdk/test/versioning/bucketDelete.js, tests/functional/aws-node-sdk/test/versioning/listObjectMasterVersions.js, tests/functional/aws-node-sdk/test/versioning/listObjectVersions.js, tests/functional/aws-node-sdk/test/versioning/multiObjectDelete.js, tests/functional/aws-node-sdk/test/versioning/objectACL.js, tests/functional/aws-node-sdk/test/versioning/objectCopy.js, tests/functional/aws-node-sdk/test/versioning/objectDelete.js, tests/functional/aws-node-sdk/test/versioning/objectGet.js, tests/functional/aws-node-sdk/test/versioning/objectHead.js, tests/functional/aws-node-sdk/test/versioning/objectPut.js, tests/functional/aws-node-sdk/test/versioning/objectPutCopyPart.js, tests/functional/aws-node-sdk/test/versioning/versioningGeneral1.js, tests/functional/aws-node-sdk/test/versioning/versioningGeneral2.js, tests/unit/metadata/bucketfile/backend.js
This replaces PR https://github.com/scality/S3/pull/690 (adapt to refactoring of level-net + ticket number fix).
Linked to Arsenal PR https://github.com/scality/Arsenal/pull/245.
=> S3C-193 bucketfile versioning support

lib/auth/in_memory/backend.js, lib/auth/in_memory/indexer.js, tests/functional/aws-node-sdk/test/bucket/put.js
=> FIX: put Bucket as a user

DockerfileMem
=> DOCKER: update DockerFile mem

constants.js, lib/api/api.js, lib/api/apiUtils/authorization/prepareRequestContexts.js, lib/api/apiUtils/object/tagging.js, lib/api/objectPutTagging.js, lib/routes/routePUT.js, tests/functional/aws-node-sdk/lib/utility/tagging.js, tests/functional/aws-node-sdk/test/object/putObjTagging.js, tests/functional/aws-node-sdk/test/versioning/objectTagging.js, tests/unit/api/objectPutTagging.js, tests/unit/helpers.js
ARSENAL: https://github.com/scality/Arsenal/pull/248
UTAPI: https://github.com/scality/utapi/pull/127
INTEGRATION: https://github.com/scality/Integration/tree/ft/putobjecttagging
=> FT: putObjectTagging

lib/api/apiUtils/authorization/aclChecks.js, lib/api/objectPutTagging.js, tests/functional/aws-node-sdk/test/object/putObjTagging.js
- adding the right ACL permission
- renaming CORSHeaders variable
=> FIX: putObjectTagging

tests/functional/aws-node-sdk/test/versioning/objectDelete.js
AWS has this description in its [REST API](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectDELETE.html) which is different from our own implementation: The DELETE operation removes the null version (if there is one) of an object and inserts a delete marker, which becomes the current version of the object. If there isn't a null version, Amazon S3 does not remove any objects.
These tests were run against AWS and verify despite what the description implies, that our implementation is compatible's with AWS's. The DELETE operation only removes the null version if versioning is suspended, not if it is enabled.
=> test: creating delete markers w/ null ver

lib/api/api.js, lib/api/apiUtils/authorization/prepareRequestContexts.js, lib/api/objectDeleteTagging.js, lib/routes/routeDELETE.js, tests/functional/aws-node-sdk/test/object/deleteObjTagging.js, tests/functional/aws-node-sdk/test/versioning/objectDeleteTagging.js, tests/unit/api/objectDeleteTagging.js
UTAPI: https://github.com/scality/utapi/pull/130
ARSENAL: https://github.com/scality/Arsenal/pull/255
INTEGRTION: https://github.com/scality/Integration/compare/ft/deleteobjecttagging
=> FT: deleteObjectTagging

lib/api/bucketGetVersioning.js, lib/api/bucketPutVersioning.js, lib/api/multiObjectDelete.js, lib/api/objectCopy.js, lib/api/objectDelete.js, lib/api/objectPut.js
Depends on https://github.com/scality/utapi/pull/129.
Update APIs to push correct metrics for changes related to versioning.
=> FT: Handle Utapi metrics for versioning

lib/api/apiUtils/authorization/prepareRequestContexts.js, lib/api/objectCopy.js, lib/services.js, tests/functional/aws-node-sdk/test/object/objectCopy.js, tests/functional/aws-node-sdk/test/versioning/objectCopy.js
objectCopy with tags
Integration PR: https://github.com/scality/Integration/pull/529
=> FT: objectCopy with tags

.babelrc, package.json, tests/functional/aws-node-sdk/.babelrc, tests/functional/raw-node/test/mocha.opts, tests/unit/auth/V4Transform.js
Missed some babel stuff in previous clean-up.
=> cleanup: remove babel remnants

lib/routes/routesUtils.js, lib/utilities/retrieveData.js, package.json
S3C-429
Prevent memory problems by no longer double buffering.
=> FIX: Only stream from one data location at a time.

constants.js, lib/api/api.js, lib/api/apiUtils/bucket/getReplicationConfiguration.js, lib/api/apiUtils/bucket/models/ReplicationConfiguration.js, lib/api/bucketPutReplication.js, lib/metadata/BucketInfo.js, lib/routes/routePUT.js, lib/utilities/parseXML.js, tests/functional/aws-node-sdk/lib/utility/replication.js, tests/functional/aws-node-sdk/test/bucket/putBucketReplication.js, tests/unit/api/bucketPutReplication.js, tests/unit/bucket/BucketInfo.js
Depends on https://github.com/scality/Arsenal/pull/258/files.
=> FT: Add bucketPutReplication API

lib/metadata/models/object/ObjectMD.js, lib/metadata/wrapper.js, lib/services.js, tests/unit/metadata/models/object.js
Using a class to compute regular object
metadata
=> REFACTOR: Metadata object using class

lib/auth/vault.js
=> S3C-380: Get security token

lib/routes.js
=> LOG: Add endpoint log

circle.yml, lib/data/locationConstraintParser.js, lib/data/multipleBackendGateway.js, tests/functional/aws-node-sdk/test/multipleBackend/get.js, tests/functional/aws-node-sdk/test/multipleBackend/put.js
This PR fixes multiple backend tests that were not being run and their socket hangups
=> Fix multiple backend tests

lib/data/external/AwsClient.js, lib/data/locationConstraintParser.js, lib/data/multipleBackendGateway.js, lib/data/multipleBackendLogger.js
Update backendGateway to extract external data backends.
=> REFACTO: multiple backend gateway

lib/Config.js, tests/unit/testConfigs/cosParse.js, tests/unit/testConfigs/sproxydAssert.js
chordChos must be 1 digit string smaller than 7
fix S3C-531
=> BF S3C-531 chordChos must be 1 digit string smaller than 7

circle.yml, tests/multipleBackend/objectPut.js, tests/multipleBackend/objectPutCopyPart.js, tests/multipleBackend/objectPutPart.js
It all started with some mocha 'it's that should've been 'describe's, which meant some tests weren't updated in the last few PR's that should've been. This PR fixes the describes, removes an unnecessary error check, and runs the tests with mdserver.js
=> Update how multiple backend tests are run

lib/api/bucketPut.js
=> FT: More info on location err message

DockerfileMem, docker-entrypoint.sh
- Replacing `sed` to `jq` in _config.js_
- Installing `jq` when creating Docker in-memory Image
=> replace sed to jq + add jq to DockerFileMem

circle.yml, lib/api/apiUtils/object/prepareStream.js, lib/api/apiUtils/object/storeObject.js, lib/api/completeMultipartUpload.js, lib/api/initiateMultipartUpload.js, lib/api/objectPutPart.js, lib/data/external/AwsClient.js, lib/data/multipleBackendGateway.js, tests/functional/fog/tests.rb, tests/multipleBackend/multipartUpload.js, tests/multipleBackend/objectPut.js, tests/multipleBackend/objectPutPart.js
Adds implementation of MPU basics to AWS backend
=> Add MPU initiate/complete and putPart for AWS

docs/ARCHITECTURE.rst
Will need @nicolas2bert's help to figure out how to render the documents for preview on the readthedocs :smile:
See rendered changes here: http://s3-server.readthedocs.io/en/doc-adddoc/ARCHITECTURE/#versioning
=> ft: update versioning doc to reflect changes

lib/data/external/AwsClient.js, lib/data/locationConstraintParser.js, lib/data/multipleBackendGateway.js, lib/data/wrapper.js, tests/functional/aws-node-sdk/lib/utility/createEncryptedBucket.js, tests/functional/aws-node-sdk/test/multipleBackend/get.js, tests/functional/aws-node-sdk/test/multipleBackend/put.js, tests/functional/aws-node-sdk/test/object/copyPart.js, tests/functional/aws-node-sdk/test/support/awsConfig.js, tests/multipleBackend/objectPutPart.js
On a PUT request to AWS backend, AWS will handle encryption.
=> Allow AWS to handle encryption

docker-entrypoint.sh, docs/DOCKER.rst
http://s3-server.readthedocs.io/en/doc-adddoc/DOCKER/#s3data-multiple
=> DOC: fix data=multiple

lib/api/apiUtils/bucket/models/ReplicationConfiguration.js, tests/functional/aws-node-sdk/lib/utility/replication.js, tests/functional/aws-node-sdk/test/bucket/putBucketReplication.js
Enforce the destination value bucket ARN.
=> COMPAT: Add check for destination bucket ARN

conf/authdata.json, lib/routes/routeBackbeat.js, lib/utilities/internalHandlers.js, tests/functional/aws-node-sdk/lib/utility/bucket-util.js, tests/functional/raw-node/test/routes/routeBackbeat.js, tests/functional/raw-node/utils/makeRequest.js
Add internal routes to allow backbeat to put raw data and metadata on destination
part of backbeat replication extension
https://scality.atlassian.net/browse/S3C-349
=> S3C-349 backbeat routes

lib/api/completeMultipartUpload.js, tests/functional/aws-node-sdk/test/object/mpuOrder.js, tests/unit/api/multipartUpload.js
=> FIX: completeMPU

docker-entrypoint.sh, docs/DOCKER.rst
This PR adds:
- ENDPOINT environment variable ( ENDPOINT === HOST_NAME)
- secret credentials for Zenko
=> DOCKER: adding ENDPOINT and secret credentials

tests/multipleBackend/multipartUpload.js
I had to learn the hard way not to cheat with changing global vars. This PR moves any changing variables in the multipleBackend MPU test suite (the only offender) to the local scope. Should also help with some of the AWS socket hangups
=> Remove changed global vars

lib/api/apiUtils/bucket/models/ReplicationConfiguration.js, tests/functional/aws-node-sdk/lib/utility/replication.js, tests/functional/aws-node-sdk/test/bucket/deleteBucketReplication.js, tests/functional/aws-node-sdk/test/bucket/getBucketReplication.js, tests/functional/aws-node-sdk/test/bucket/putBucketReplication.js, tests/functional/aws-node-sdk/test/object/objectHead_replication.js, tests/unit/api/bucketPutReplication.js, tests/unit/api/objectReplicationMD.js, tests/unit/bucket/BucketInfo.js, tests/unit/metadata/models/object.js
Depends on https://github.com/scality/Integration/pull/543.
=> FT: Include two roles in bucket replication config

lib/api/listParts.js, lib/api/multipartDelete.js, lib/data/external/AwsClient.js, lib/data/multipleBackendGateway.js, lib/services.js, tests/multipleBackend/multipartUpload.js
Implements the listParts API for AWS backend
=> ListParts for AWS backend

constants.js, lib/Config.js, lib/api/apiUtils/object/createAndStoreObject.js, lib/data/external/AwsClient.js, lib/data/external/AzureClient.js, lib/data/locationConstraintParser.js, lib/data/multipleBackendGateway.js, lib/data/wrapper.js, locationConfig.json, package.json, tests/functional/aws-node-sdk/test/multipleBackend/put/put.js, tests/functional/aws-node-sdk/test/multipleBackend/put/putAzure.js, tests/multipleBackend/objectPut.js
- Config
- Health-checks
- Put
=> FT: AZURE - Config and PUT

tests/functional/aws-node-sdk/test/multipleBackend/put/putAzure.js
This PR should fix Azure flaky tests
=> FX: Flaky Azure Tests

lib/api/objectGet.js, tests/functional/aws-node-sdk/test/object/get.js
Depends on https://github.com/scality/Arsenal/pull/309.
=> FT: Add PartNumber support for getObject

config.json, lib/Config.js, lib/metadata/wrapper.js, mdserver.js
Enable or disable record log service provided in https://github.com/scality/Arsenal/pull/253
=> bucketfile record log service for backbeat

lib/api/apiUtils/object/createAndStoreObject.js, lib/api/objectDeleteTagging.js, lib/api/objectPutTagging.js, lib/data/external/AwsClient.js, lib/data/multipleBackendGateway.js, lib/services.js, tests/functional/aws-node-sdk/test/multipleBackend/objectTagging.js
Implement object tagging for AWS backend.
Depends on Arsenal#310
=> FT: AWS TAGGING

lib/api/objectPutCopyPart.js, lib/api/objectPutPart.js, lib/data/external/AwsClient.js, lib/data/multipleBackendGateway.js, tests/multipleBackend/objectPutCopyPart.js
Implement objectPutCopyPart API for AWS backend
=> ft: Add ObjectPutCopyPart for AWS backend

docker-entrypoint.sh
Allow zenko to configure record log
=> FT: Enable configuration of record log

lib/Config.js, lib/data/file/backend.js, lib/data/in_memory/backend.js, lib/data/locationConstraintParser.js, lib/data/multipleBackendLogger.js, lib/data/wrapper.js, lib/metadata/bucketfile/backend.js, lib/metadata/wrapper.js, lib/utilities/logger.js
Adapt S3 to recent werelogs API changes, solving the issue of misconfiguration of the logging system.
Internal: S3C-703
The issue was not covered by the tests previously; I'm leaving adding a new test to you guys, as this fix is wide in impact on the connector.
=> S3C-703: Update werelogs config handling

docker-entrypoint.sh
Before overwriting config.json, confirm changes
have been made with env variables.
=> FIX: Check whether config.json changes

lib/routes/routeBackbeat.js
Depends on https://github.com/scality/backbeat/pull/65.
=> FT: Send key and dataStoreName for putData response

tests/functional/aws-node-sdk/test/multipleBackend/delete/delete.js, tests/functional/aws-node-sdk/test/multipleBackend/delete/deleteAzure.js
This PR adds tests for Azure Delete
=> TEST: Azure DELETE

docs/CLIENTS.rst
=> Doc added period

lib/api/corsPreflight.js, lib/api/serviceGet.js, tests/functional/aws-node-sdk/test/object/corsHeaders.js, tests/functional/aws-node-sdk/test/object/corsPreflight.js, tests/unit/api/serviceGet.js
- allow and return headers in preflight for get service
- add cors headers in get service
=> Allow CORS headers for get service

docs/DOCKER.rst, lib/api/objectCopy.js, lib/data/external/AwsClient.js, lib/data/external/utils.js, lib/data/multipleBackendGateway.js, tests.bash, tests/functional/aws-node-sdk/test/multipleBackend/objectCopy.js, tests/functional/aws-node-sdk/test/multipleBackend/put/put.js, tests/locationConfigTests.json
=> FIX: Object Copy to AWS

tests/functional/aws-node-sdk/test/multipleBackend/delete/deleteAzure.js, tests/functional/aws-node-sdk/test/multipleBackend/mpuParts/azurePutPart.js, tests/functional/aws-node-sdk/test/multipleBackend/put/putAzure.js, tests/locationConfigTests.json
Testing Azure location Constraint with bucketMatch sets to false.
=> TEST: Azure with BucketMatch equals false

constants.js, lib/api/apiUtils/object/createAndStoreObject.js, lib/api/objectGet.js, lib/data/external/AwsClient.js, lib/data/external/AzureClient.js, lib/data/multipleBackendGateway.js, tests/functional/aws-node-sdk/test/multipleBackend/get/get.js, tests/functional/aws-node-sdk/test/multipleBackend/get/getAwsVersioning.js, tests/functional/aws-node-sdk/test/multipleBackend/get/getAzure.js, tests/functional/aws-node-sdk/test/multipleBackend/put/put.js, tests/functional/aws-node-sdk/test/multipleBackend/utils.js, tests/functional/aws-node-sdk/test/object/objectCopy.js, tests/functional/aws-node-sdk/test/versioning/objectPut.js
=> ft: enable versioning put/get for aws backend

README.md
=> DOCS: Troubleshoot npm install

lib/api/apiUtils/bucket/models/ReplicationConfiguration.js, tests/functional/aws-node-sdk/test/bucket/putBucketReplication.js
To be forward ported through to master branch in S3 and Arsenal.
=> FIX: Check only defined replication rule IDs

tests/functional/aws-node-sdk/test/multipleBackend/delete/delete.js, tests/functional/aws-node-sdk/test/multipleBackend/delete/deleteAwsVersioning.js, tests/functional/aws-node-sdk/test/multipleBackend/delete/deleteAzure.js, tests/functional/aws-node-sdk/test/multipleBackend/get/get.js, tests/functional/aws-node-sdk/test/multipleBackend/get/getAwsVersioning.js, tests/functional/aws-node-sdk/test/multipleBackend/get/getAzure.js, tests/functional/aws-node-sdk/test/multipleBackend/initMPU/initMPUAzure.js, tests/functional/aws-node-sdk/test/multipleBackend/listParts/azureListParts.js, tests/functional/aws-node-sdk/test/multipleBackend/mpuAbort/azureAbortMPU.js, tests/functional/aws-node-sdk/test/multipleBackend/mpuComplete/azureCompleteMPU.js, tests/functional/aws-node-sdk/test/multipleBackend/mpuParts/azurePutPart.js, tests/functional/aws-node-sdk/test/multipleBackend/objectCopy/azureObjectCopy.js, tests/functional/aws-node-sdk/test/multipleBackend/objectCopy/objectCopy.js, tests/functional/aws-node-sdk/test/multipleBackend/objectTagging/objectTagging.js, tests/functional/aws-node-sdk/test/multipleBackend/put/put.js, tests/functional/aws-node-sdk/test/multipleBackend/put/putAzure.js, tests/functional/aws-node-sdk/test/multipleBackend/utils.js
I copied functions and some constants to the utils for previous pull requests, but left the clean-up to afterwards so the pull request wouldn't be too long. This is the clean-up PR.
=> chore: clean tests to use multiple backend utils

tests/functional/aws-node-sdk/test/bucket/putBucketReplication.js
Depends on https://github.com/scality/Arsenal/pull/360.
=> FWD: rel/7.0 to rel/7.1

lib/api/apiUtils/object/setPartRanges.js, lib/api/objectGet.js
This fixes the range passed to setPartRanges() as an inclusive range
Forward-port of https://github.com/scality/S3/pull/975.
=> forward port to master of bf: fix MPU object GET + PartNumber

lib/api/apiUtils/object/setPartRanges.js, lib/api/objectGet.js
This fixes the range passed to setPartRanges() as an inclusive range.
Replaces https://github.com/scality/S3/pull/974.
=> fix MPU object GET + PartNumber

lib/metadata/bucketclient/backend.js, tests/unit/metadata/bucketclient/backend.js
S3C-1038
Adds additional error handling
Test Cases:
* Error Case: Verifies that listMultiPartUploads works in an error case
* Success Case: Verifies that listMultiPartUploads works in a success case.
=> FIX: JSON parse on an undefined

lib/metadata/bucketclient/backend.js, tests/unit/metadata/bucketclient/backend.js
Forward from rel/6.3 to rel/6.4
FIX: JSON parse on an undefined
=> Forward: rel/6.3 to rel/6.4

tests/functional/aws-node-sdk/test/multipleBackend/delete/deleteAwsVersioning.js, tests/functional/aws-node-sdk/test/multipleBackend/put/put.js, tests/functional/aws-node-sdk/test/multipleBackend/utils.js
On the last successful [end to end](http://ci.ironmann.io/gh/scality/Integration/16932), it took 2 hours to run multiple backend tests. Trying to see if omitting the timeout on the first attempt to get data directly from AWS can reduce the run-length at all.
=> chore: omit timeout on first try - multi tests

lib/api/multiObjectDelete.js, tests/functional/aws-node-sdk/test/object/multiObjectDelete.js
S3C-1063 
Adds a check to handle cases in which multiObjectDelete is passed an empty list
=> FX: Checks multiObjectDelete Empty Case

tests/functional/aws-node-sdk/test/legacy/authV2QueryTests.js
https://github.com/scality/Arsenal/pull/370
=> S3C-885: Change v2 query auth window to 7 days

lib/api/apiUtils/authorization/prepareRequestContexts.js
Tests: https://github.com/scality/Integration/pull/595
=> S3C-1096 Use X-Forwarded-For header to get client IP

tests/functional/aws-node-sdk/test/multipleBackend/delete/delete.js
Changes 'putObject' to 'putObjectAsync'
=> FX: func. delete's before hook

config.json, lib/Config.js, lib/data/wrapper.js, lib/metadata/wrapper.js
Why is this change required? What problem does it solve?
Please use the following link syntaxes #600 to reference issues in the
current repository
New tests added or existing tests modified to cover all changes
In order to contribute to the project, you must sign your work
https://github.com/scality/Guidelines/blob/master/CONTRIBUTING.md#sign-your-work
Thank you again for contributing! We will try to test and integrate the change
as soon as we can.
=> S3 c 1103 readonly

lib/api/bucketPutVersioning.js, lib/api/initiateMultipartUpload.js, tests/functional/aws-node-sdk/test/multipleBackend/put/putAzure.js
(cherry picked from commit bc8c53ab3ad4ccc2fe8ce6d8dac4a53f2ff23c29)
=> BACKPORT: fix: error on versioning put to azure loc bucket

circle.yml, lib/data/locationConstraintParser.js, tests.bash
Enables running external backend tests through http proxy
=> Ft: Ext backend proxy tests

lib/api/corsPreflight.js, lib/api/serviceGet.js, tests/functional/aws-node-sdk/test/object/corsHeaders.js, tests/functional/aws-node-sdk/test/object/corsPreflight.js, tests/unit/api/serviceGet.js
Depends on https://github.com/scality/Arsenal/pull/384
=> Revert/7.2 get service cors [S3C-1009]

lib/Config.js, lib/api/bucketPut.js, lib/data/multipleBackendGateway.js, tests/unit/api/bucketPut.js, tests/unit/multipleBackend/setLocationConstraints.js
This PR is the first step in allowing the location constraints to be updated dynamically.
=> FT: Add Config::setLocationConstraints

lib/api/bucketGet.js, lib/metadata/in_memory/backend.js, tests/functional/aws-node-sdk/test/versioning/listObjectVersions.js
Depends on https://github.com/scality/Integration/pull/616
=> forward port rel/7.0 into rel/7.1

lib/data/external/GCP/GcpService.js, lib/data/external/GCP/GcpSigner.js, lib/data/external/GCP/gcp-2017-11-01.api.json, lib/data/external/GCP/index.js
Adds the base files for building the GCP service using the AWS-SDK.
=> S3C-1115 FT: Adds GCP Base Files

lib/api/apiUtils/object/getReplicationInfo.js, lib/routes/routeBackbeat.js, tests/unit/api/objectReplicationMD.js
* Add azure type for replication information.
=> FT: Add azure type for replication information

lib/data/wrapper.js
backport of https://github.com/scality/S3/pull/774 to rel/6.3
Tied to https://github.com/scality/sproxydclient/pull/128
=> backport of #774

lib/api/bucketGet.js
Update livy Client format based on changes in https://github.com/scality/Arsenal/pull/393
=> rf: update Livy Client

config.json, lib/api/apiUtils/object/getReplicationInfo.js, lib/utilities/collectResponseHeaders.js, tests/functional/aws-node-sdk/lib/utility/replication.js, tests/functional/aws-node-sdk/test/bucket/putBucketReplication.js, tests/functional/raw-node/test/routes/routeBackbeat.js, tests/unit/api/bucketPutReplication.js, tests/unit/api/objectReplicationMD.js
Depends on https://github.com/scality/Arsenal/pull/390.
=> FT: Multiple replication config storage classes

lib/Config.js, lib/api/apiUtils/authorization/aclChecks.js, lib/api/bucketGet.js, lib/data/external/AzureClient.js, lib/management.js, lib/metadata/bucketfile/backend.js, lib/metadata/wrapper.js
=> bf: fix linter errors

lib/Config.js, lib/api/apiUtils/object/getReplicationInfo.js, lib/api/objectDeleteTagging.js, lib/api/objectPutTagging.js, lib/routes/routeBackbeat.js, lib/utilities/collectResponseHeaders.js, tests/functional/aws-node-sdk/test/bucket/putBucketReplication.js, tests/unit/api/objectReplicationMD.js
Depends on https://github.com/scality/backbeat/pull/162.
Depends on https://github.com/scality/Arsenal/pull/394.
=> FT: Update replication info for one-to-many

lib/auth/in_memory/builder.js
=> TEMP: Special treatment for clueso

config.json
=> Fix: Revert default log level to info

lib/management.js
=> TEMP: Disable remote mgmt for mem

Dockerfile, DockerfileMem
=> Fix: Update exposed port

lib/data/external/GCP/GcpService.js, lib/data/external/GCP/gcp-2017-11-01.api.json, tests/functional/raw-node/test/GCP/bucket/get.js, tests/functional/raw-node/test/GCP/bucket/getVersioning.js, tests/functional/raw-node/test/GCP/bucket/head.js, tests/functional/raw-node/test/GCP/bucket/putVersioning.js, tests/functional/raw-node/test/GCP/object/delete.js, tests/functional/raw-node/test/GCP/object/get.js, tests/functional/raw-node/test/GCP/object/head.js, tests/functional/raw-node/test/GCP/object/put.js
Reference docs:
PUT: https://cloud.google.com/storage/docs/xml-api/put-object-upload
GET: https://cloud.google.com/storage/docs/xml-api/get-object-download
HEAD: https://cloud.google.com/storage/docs/xml-api/head-object
DELETE: https://cloud.google.com/storage/docs/xml-api/delete-object
=> Ft/s3 c 1115/gcp apis object

package.json, tests/functional/aws-node-sdk/test/multipleBackend/listParts/azureListParts.js
Why is this change required? What problem does it solve?
Please use the following link syntaxes #600 to reference issues in the
current repository
New tests added or existing tests modified to cover all changes
In order to contribute to the project, you must sign your work
https://github.com/scality/Guidelines/blob/master/CONTRIBUTING.md#sign-your-work
Thank you again for contributing! We will try to test and integrate the change
as soon as we can.
=> Fwdport 7.4 master

lib/data/external/GCP/GcpService.js, lib/data/external/GCP/gcp-2017-11-01.api.json, lib/data/external/GcpClient.js, lib/data/external/utils.js, lib/data/multipleBackendGateway.js, tests/functional/raw-node/test/GCP/README.MD, tests/functional/raw-node/test/GCP/bucket/get.js, tests/functional/raw-node/test/GCP/bucket/getVersioning.js, tests/functional/raw-node/test/GCP/bucket/head.js, tests/functional/raw-node/test/GCP/bucket/putVersioning.js, tests/functional/raw-node/utils/gcpUtils.js, tests/locationConfig/locationConfigTests.json
Changing base from master to feature branch ft/GCP
Refer to #1093
=> S3C-1115 FT: Adds GCP Backend healthcheck

package.json
This was installing the wrong client driver and causing problems
=> remove problematic mongodb version in package.json

lib/data/external/GCP/GcpService.js, lib/data/external/GCP/gcp-2017-11-01.api.json, tests/functional/raw-node/test/GCP/bucket/get.js, tests/functional/raw-node/test/GCP/bucket/getVersioning.js, tests/functional/raw-node/test/GCP/bucket/head.js, tests/functional/raw-node/test/GCP/bucket/putVersioning.js, tests/functional/raw-node/test/GCP/object/delete.js, tests/functional/raw-node/test/GCP/object/get.js, tests/functional/raw-node/test/GCP/object/head.js, tests/functional/raw-node/test/GCP/object/put.js
Changing base from master to feature branch ft/GCP
Refer to #1095 
Also includes the fix, but separate to show the commit history done on master.
Refer to #1107
=> Ft/s3 c 1115/gcp object

constants.js, lib/api/apiUtils/object/processMpuParts.js, lib/data/external/GCP/GcpApis/abortMPU.js, lib/data/external/GCP/GcpApis/completeMPU.js, lib/data/external/GCP/GcpApis/copyObject.js, lib/data/external/GCP/GcpApis/createMPU.js, lib/data/external/GCP/GcpApis/deleteObjects.js, lib/data/external/GCP/GcpApis/index.js, lib/data/external/GCP/GcpApis/listParts.js, lib/data/external/GCP/GcpApis/mpuHelper.js, lib/data/external/GCP/GcpApis/rewriteObject.js, lib/data/external/GCP/GcpApis/uploadPart.js, lib/data/external/GCP/GcpApis/uploadPartCopy.js, lib/data/external/GCP/GcpService.js, lib/data/external/GCP/GcpUtils.js, lib/data/external/GCP/gcp-2017-11-01.api.json, lib/data/external/GcpClient.js, package.json, tests/functional/raw-node/test/GCP/object/completeMpu.js, tests/functional/raw-node/test/GCP/object/deleteMpu.js, tests/functional/raw-node/test/GCP/object/initiateMpu.js, tests/functional/raw-node/utils/gcpUtils.js
Review: a1e4ccb0083f62b1ee2cdbbb062cdeb2def581d3
Fix: 4e3c8af22d5666ce0bb5365f078f8e09fc3d0fef
Reference Doc:
Compose Method: https://cloud.google.com/storage/docs/xml-api/put-object-compose
Limits on Composite Objects: https://cloud.google.com/storage/docs/composite-objects
Rewrite Method: https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite
Batch Operations: https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch
=> Ft/s3 c 1179/gcp mpu

lib/data/external/GCP/GcpManagedUpload.js, lib/data/external/GCP/GcpService.js, tests/functional/raw-node/test/GCP/object/upload.js
Review: cf5c359439810c32deff91179744f4b4a2b04f59
Fix: 0325c2338cafc88be54c5e1695d067dd1a5988b3
=> Ft/s3 c 1179/gcp managed upload

constants.js, lib/data/external/GCP/GcpApis/createMPU.js, lib/data/external/GCP/GcpApis/deleteTagging.js, lib/data/external/GCP/GcpApis/getTagging.js, lib/data/external/GCP/GcpApis/index.js, lib/data/external/GCP/GcpApis/putObject.js, lib/data/external/GCP/GcpApis/putTagging.js, lib/data/external/GCP/GcpUtils.js, lib/data/external/GCP/gcp-2017-11-01.api.json, tests/functional/raw-node/test/GCP/object/deleteTagging.js, tests/functional/raw-node/test/GCP/object/getTagging.js, tests/functional/raw-node/test/GCP/object/initiateMpu.js, tests/functional/raw-node/test/GCP/object/putTagging.js, tests/functional/raw-node/utils/gcpUtils.js
Review: d19262edf2c0fd1ae98bdb1c471a9f619d154a4b
=> Ft/s3 c 1183/gcp tagging

lib/management.js
Endpoint definition is done on Orbit side: https://github.com/scality/pensieve-front/pull/149/files#diff-8e64ef94b9b5ed550979ed5b114de95eR10
=> FT: ZENKO-118: Add support for Wasabi data backend

lib/data/locationConstraintParser.js, lib/server.js, package.json, tests/unit/api/bucketPutLifecycle.js, tests/unit/utils/lifecycleHelpers.js, tests/unit/utils/responseStreamData.js
=> foward port rel/7.4 to foward/orbit

lib/management.js
Adds management support creating GCP location configurations
=> FT: Adds support for GCP data backend

lib/api/bucketPutLifecycle.js, lib/metadata/ModelVersion.md
Update the ModelVersion.md file
=> ft: update ModelVersion.md

conf/authdata.json, lib/api/apiUtils/authorization/aclChecks.js, lib/api/apiUtils/bucket/bucketCreation.js, lib/auth/in_memory/builder.js, lib/management.js, package-lock.json, tests/functional/aws-node-sdk/lib/json/mem_credentials.json, tests/functional/aws-node-sdk/test/bucket/putBucketReplication.js, tests/functional/aws-node-sdk/test/bucket/testBucketVersioning.js
This PR grants '/replication' user permission to read and write any buckets and objects.
=> FX: granting '/replication' user permission to read/write buckets and objects

lib/api/objectDelete.js, tests/unit/api/objectDelete.js
(cherry picked from commit a02d226b4c4645a0f8bf7ce862960945d0c43951)
=> backport master to rel/7.4-beta

lib/api/bucketPutLifecycle.js, lib/metadata/ModelVersion.md
Bucket property uid is added to all buckets, updating ModelVersion.md to reflect the change
=> ft: edit ModelVersion usage of property uid on buckets

docs/MD_SEARCH.md, examples/go-md-search.go, examples/node-md-search.js, examples/python-md-search.py
+ Written explanation of exactly how to use MD search with our expanded API.
+ Coding examples similar to the utilization API request (i.e., examples of how to use the expanded API tool)
=> doc: ZENKO-259 MD Search

circle.yml, docs/mkdocs.yml, lib/utilities/reportHandler.js
Relies on https://github.com/scality/Arsenal/pull/491
=> bf: ZENKO-355 crr stats byte conversion
