scality/cloudserver

tests/functional/s3cmd/package.json, tests/functional/s3curl/package.json
- Since recent changes, the branch rel/1.0 of arsenal was
removed and replaced by rel/1.1, this commit fix the branch
dependencies against rel/1.1
=> [Tests](fix): Tests dependencies (rel/1.1)

tests/functional/s3cmd/package.json, tests/functional/s3curl/package.json
- Since recent changes, the branch rel/1.0 of arsenal
was removed, this commit fix the branch dependencies
=> [Tests](fix): Tests dependencies

init.js, package.json
ioctl install fails on CentOS7 aborting the whole npm install
process. Adding it as an optional depedency allow npm to continue
if the dependency install fails.
Fix #61
=> BF: optionally install ioctl dependency

constants.js, lib/api/bucketGet.js
Reopening against rel/1.1
- Amazon aws sets a hard limit to 1000
This config can be override in constants.js to increase or
decrease the max keys we will receive
see http://docs.aws.amazon.com/AmazonS3/latest/API/
RESTBucketGET.html#RESTBucketGET-requests
=> [Listing](ft): Set an hard limit to listing

Dockerfile
Build :
-> `docker build -t 'test:1.0' ./`
Run with volumes :
-> `docker run -d -P -v /tmp/localData:/usr/src/app/localData -v /tmp/localMetadata:/usr/src/app/localMetadata test:1.0`
->  When running Dockerfile on macOS, there is an issue with the function : **_setDirSyncFlag** on init.js and the levelup and leveldown with levelDB.
Working fine when running directly on linux / linux VM.
=> Testing with Dockerfile

lib/server.js
If the backend is anything other than 'mem', the number of workers should be set by the config.
=> Specify backend variable for one worker.

lib/data/file/backend.js
See https://nodejs.org/api/fs.html#fs_fs_open_path_flags_mode_callback
'w' - Open file for writing. The file is created (if it does not exist) or truncated (if it exists).
'wx' - Like 'w' but fails if path exists.
=> Prevent overriding of file if hash collision.

lib/api/bucketGet.js, lib/api/listMultipartUploads.js, lib/api/listParts.js, tests/unit/api/bucketGet.js
**bucketGet.js** : 
-  max-keys can not be negative,
if the value is negative we return an error message to the user " errors.InvalidArgument".
**listParts.js** : 
- Making 1000 uploads, the maximum number of uploads a response can include.
- Making 1000 the default value.
- The response can not include negative value,
if the value is negative we return an error message to the user " errors.InvalidArgument".
[http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadListParts.html](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadListParts.html)
**listMultipartUploads.js** :
- Making 1000 multipart uploads, the maximum number of uploads a response can include.
- Making 1000 the default value.
- The response can not include negative value,
if the value is negative we return an error …
=> BF: Limiting maxKeys/maxUploads/maxParts

lib/routes/routesUtils.js, package.json, tests/functional/s3cmd/tests.js
Uses double buffering to increase the speed of gets of objects put by MPU.
Perf testing with 1GB object:
205 parts with specified part size of 5MB
-with rel/1.1:  about 13-14 seconds
-with double buffer: about 7-8 seconds
103 parts with specified part size of 10 MB
-with rel/1.1: about 15-16 seconds
-with double buffer: about 7-8 seconds
52 parts with specified part size of 20 MB
-with rel/1.1: about 12-13 seconds
-with double buffer: about 5-6 seconds
=> Perf--gets of objects put by MPU

README.md
EPEL for Centos 7 for example ships with nodejs 0.10 so people need to be aware.
=> Document minimum node.js version

constants.js, lib/api/api.js, lib/api/bucketGet.js, lib/api/listMultipartUploads.js, lib/api/listParts.js, lib/api/objectDelete.js, lib/metadata/wrapper.js, lib/utilities/escapeForXML.js, tests/functional/aws-node-sdk/test/bucket/get.js, tests/functional/aws-node-sdk/test/legacy/tests.js, tests/unit/api/bucketGet.js
The forward-port of rel/1.1 to rel/1.1-smartbulb was already done, so here is the step that will bring all the required changes to master.
As there were a few conflicts, @rahulreddy @LaurenSpiegel Could you please check this over, and validate that everything's good here ? We'll run the end-to-end CI anyways.
Once this is merged, people should automatically forward-port their changes from one branch to another (reminder, at the moment the order is:  rel/1.1 -> rel/1.1-smartbulb -> master)
=> Forward-port of rel/1.1-smartbulb into master

lib/services.js
Tests are not handling the case when S3 returns an [error](https://github.com/scality/S3/blob/master/lib/services.js#L337) if users delete an object with a versioning-enabled metadata backend.
This PR fixes the behavior of S3 instead of changing the tests; S3 will not return the error and will continue to delete the object in metadata in such case. This ensures the same metadata behavior though with different backends (versioning and non-versioning).
This fix is also inline with how S3 should handled versioning in future versions.
=> deleteObject's compat. w/ versioning

lib/api/apiUtils/bucket/bucketCreation.js, lib/metadata/BucketInfo.js, lib/metadata/ModelVersion.md, lib/metadata/bucketfile/backend.js, lib/services.js, tests/unit/api/listParts.js, tests/unit/bucket/BucketInfo.js
We are manually updating the BucketInfo model version a number of places in the code where BucketInfo is instantiated.  This is likely to be forgotten when changes are made to the BucketInfo model.  So, I have created a static function on the BucketInfo class which pulls the current model version.  I also added a changelog to keep track of the versions.
=> Centralize model version tracking for BucketInfo

lib/Config.js, lib/kms/in_memory/backend.js, lib/kms/wrapper.js, lib/services.js
- S3KMS environment variable added
- bucketKeyId as a number breaks sanity checks in BucketInfo
- scality-kms integration + fallback to file if not available
- location array in objectmd may be undefined
=> scality-kms integration and bug fixes

lib/api/objectDelete.js, lib/api/objectGet.js, lib/api/objectHead.js, lib/services.js, lib/utilities/collectResponseHeaders.js, lib/utilities/validateHeaders.js, tests/functional/aws-node-sdk/test/object/objectHead.js
Refactor and tests the header validation to ensure compatibility against real AWS S3 api
1) Modularizes the validateHeaders function so that 3 functions that were combined are separated: (a) checking whether the object exists, (b) checking the if-match and if-modified headers against the object metadata, (c) pulling the metadata for the response.  This impacts objectHead, deleteObject and getObject API's.
2) Fixes the if-match and if-modified header checks to deal with multiple etags provided in one request and for AWS compatibility with mixed headers (e.g., if-match and if-modified-since together in the same request).  This closes https://github.com/scality/S3/issues/125
=> Compat: header validation refactor and tests

lib/api/apiUtils/authorization/aclChecks.js, tests/unit/api/bucketACLauth.js
Fixing issue #136
When setting the 'public-read' ACL permission of the object, any account can get an object (objectGet) / get its metadata (objectHead) even if the account has no right to the bucket
=> FIX: getObject works with ACL header: public-read

lib/utilities/collectResponseHeaders.js
by return, I mean in the response header
=> should not return sse key id unless sse is aws:kms

lib/routes/routeDELETE.js, lib/routes/routeHEAD.js, lib/routes/routePOST.js
This commit adds push metrics support on bucket level for
- Initiate Multipart Upload
- Complete Multipart Upload
- Abort Multipart Upload
- Head Bucket
- Head Object
=> FT: Add push metrics for more routes

config.json
Currently it is filling up logs with push metrics errors on a default
install. Changing this to be enabled on-demand.
=> FT: disable utapi by default

lib/routes/routePUT.js
When creating bucket using a POST request: we call `pushMetricCreateBucket` from Utapi client.
=> FIX: call pushMetricCreateBucket when createbucket using POST

lib/api/objectPut.js
pushMetrics call for object PUT uses the content-length to calculate
incoming bytes, number of object counters. A null would indicate that
the object is created new and any number 0 or greater than 0 indicates
an existing object which would not alter the count of number of objects
in the bucket.
fixes #198
=> fix: pass null for push metrics on object put

lib/api/api.js, lib/auth/vault.js, lib/kms/utilities.js
This is the first step towards using the cleaned-up Auth API from arsenal.
The work is still ongoing, but this will allow us to avoid falling out-of-sync.
Depends on: https://github.com/scality/Arsenal/pull/119 then https://github.com/scality/vaultclient/pull/94
=> Use refactored Arsenal's Auth API - Step 1

init.js
As system error numbers vary across the systems, error code is used to detect
a specific error.
Fix #155
=> fix: user error code to detect system error

lib/data/file/backend.js
Fix #206 
It's possible that stream ends before the `fs.write` operation finishes.
Double checks to make sure that only one callback returns.
=> Data file backend: fix bug for put operation

constants.js, lib/api/completeMultipartUpload.js, lib/auth/in_memory/backend.js, lib/auth/in_memory/vaultUtilities.js, lib/auth/streamingV4/constructChunkStringToSign.js, lib/utils.js
in Node v4, default crypto encoding is binary, this
PR specify this encoding to avoid any change in the future
(node v6 in mind)
=> FT: Fix crypto encoding

tests/functional/jaws/pom.xml
Removed jets3t from pom.xml.
the java test are using the java amazon sdk now (and not jets3t)
Fix https://github.com/scality/S3/issues/255
Sorry for that.
=> Removed jets3t from pom.xml

tests/functional/aws-node-sdk/test/object/copyPart.js
If do not move this parsing, cannot run AWS_ON_AIR tests.
The encrypted bucket function is only meant for the S3 server.
However, by having the parsing done outside of the createEncryptedBucket function,
the process will crash before running tests with AWS_ON_AIR=true.
=> Move config parsing to encrypt bucket function.

lib/routes/routePUT.js
The second `if`has never been accessed.
_CASES:_ 
- `content-length`  undefined  && `x-amz-decoded-content-length` undefined  : **errors.MissingContentLength**(411)
- `content-length` is not an integer or is negatif: node `http` module filter the request (ie: request never reach our S3 server)
- `x-amz-decoded-content-length` is not an integer or is negatif **errors.BadRequest** (400)
=> CLEAN UP: second "if" never been accessed

lib/services.js
Fix #252
* If a method is not logging an error from metadata, then log it
* If an error object is not being handled, then log it and return
the callback, passing the error object
=> BF: Log errors or return errors from MD

DockerfileMem
We are starting adding some kind of versioning for our S3 Docker image.
On Docker, we are now pushing four tags every time we generate a new S3 image:
- **file backend** : `latest` and `HASHCOMMIT`
- **in-memory backend**: `mem-latest` and `mem-HASHCOMMIT`
I started doing it here: https://hub.docker.com/r/scality/s3server/tags/
I will add a _Supported tags and respective Dockerfile links_ inside our [scality/s3server Docker repo](https://hub.docker.com/r/scality/s3server/)
We will use [DockerfileMem](https://github.com/scality/S3/blob/dev/Dockerfile-mem/DockerfileMem) for our in-memory backend S3 image.
`docker build -t 's3mem' -f 'DockerfileMem' ./`
=> Dockerfile for mem backend

lib/api/objectCopy.js, lib/services.js, lib/utilities/collectResponseHeaders.js, tests/functional/aws-node-sdk/test/object/get.js, tests/functional/aws-node-sdk/test/object/objectCopy.js, tests/functional/aws-node-sdk/test/object/objectHead_compatibleHeaders.js
Related to issue fix #282
Optional headers Cache-Control, Content-Disposition, Content-Encoding, and Expires are missing in objectGet and objectHead response.
* Stores header values if specified in objectPut or objectCopy request.
* Returns stored values in objectGet and objectHead responses.
* Will follow-up in separate PR to address storing header values for multipartUpload
=> BF: Store / return AWS compatible headers

lib/utilities/aclUtils.js, tests/unit/api/bucketPutACL.js
FIXES #304
I checked against AWS S3 and when:
- adding multiple AccessControlList section
OR
- AccessControlList section is not empty and there is no Grant section
it returns a MalformedACLError.
If AccessControlList section is empty `<AccessControlList></AccessControlList>`, AWS does not throw any error.
=> COMPAT: set ACLs with an empty AccessControlList

lib/routes/routePUT.js, lib/services.js, tests/functional/s3curl/tests.js
Fixes https://github.com/scality/S3/issues/281
When content-md5 header is empty: return InvalidDigest error
**On [ceph/s3-tests](https://github.com/ceph/s3-tests), these changes fix**:
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_md5_empty` **should return InvalidDigest error**
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_md5_bad`  **should return BadDigest error**
when `content-md5` header mismatches the hash which has been generated.
=> COMPAT: check for empty content-md5 header

lib/api/objectGetACL.js, lib/utilities/aclUtils.js
Fix #285
* Generate the XML DOM with the function `convertToXml()` instead
of constructing a JSON object with `aclUtils.constructGetACLsJson`
and then using the xml module
=> CLEANUP: Remove xml module usage in objectGetAcl api

README.md
Update to the current node.js required version
See https://github.com/scality/S3/issues/337
=> FIX: Update readme

package.json
ioctl is already being installed as an optional dependency.
=> fix: remove redundant ioctl dependency

lib/api/bucketGetACL.js, lib/utilities/aclUtils.js, lib/utils.js
Fix #269
- Use `aclUtils.convertToXml` function to generate the XML DOM
- Remove `aclUtils.constructGetACLsJson` function because XML
is generated with the `grantInfo` object and does not need to
be formatted for the XML module
- Remove `utils.convertToXml` because its purpose was to 1) handle
JSON construction with `aclUtils.constructGetACLsJson` 2) return
the XML DOM using the XML module
=> CLEANUP: Remove xml module usage in bucketGetAcl api

lib/server.js
`http` log typo.
That can be confusing when looking at the log.
=> BF: typo https

lib/Config.js
This commit makes sure that localhost retains access to healthcheck routes
when an additional list of IP addresses are provided as a whitelist.
=> ft: append IPs to default list for healthchecks

lib/routes.js
set content-length to avoid transfer-encoding chunked on responses
fix #354
=> fix: set content-length on healthcheck route

lib/auth/streamingV4/V4Transform.js, tests/functional/fog/tests.rb
Oracle sbt appears to be adding extra line breaks between the metadata portions and data portions of the chunks in streaming v4 auth.  This PR removes the extra line breaks if any.
=> Address additional line breaks in streaming v4

Dockerfile, DockerfileMem
These changes make the Docker S3Sever container lighter from 841.4 MB to 550.8 MB.
This new image has been tested with and without HTTPS.
I think it was better to keep `git` dependency.
_use-cases:_ `git describe` to get the release and commit.
=> Dockerfile: Make s3 container lighter

lib/data/wrapper.js, lib/services.js, tests/functional/aws-node-sdk/test/object/deleteObject.js
Related to issue #312
- Add optional callback to batchDelete so it can be used to delete object(s) instead of duplicating code
- Swap order so MD is deleted before data
- Remove redundant log traces and errors
- Add functional test for deleteObject to test deleting an object uploaded in parts
This at least swaps the order of deletion so MD is deleted before data, which is preferable to potential ghost MD of a deleted data object. The issue of how to persist the delete keys for confirmation of data deletion still needs to be resolved.
=> CLEANUP: Reorder so MD is deleted before data

circle.yml, tests/functional/s3curl/tests.js
* Add the required before/after steps for each describe block in the s3curl
tests. It was done this way so that we at least get a self-contained
granularity at the describe level rather than through the whole file
* Remove the data removal steps from circle.yml as it is not longer necessary
Fix #358 
Addresses part of #359 
Note: This work is a pre-requisite to an ongoing cleanup work aimed at improving dependency patcher suport in end to end tests.
=> chore: Make s3curl ft tests self-contained

lib/api/bucketPutACL.js, lib/utilities/aclUtils.js, tests/functional/aws-node-sdk/test/bucket/putACL.js, tests/unit/api/bucketPutACL.js, tests/unit/helpers.js
FIXES #365 
Had to modify some existing unit tests to comply with new requirements.
=> COMPAT putBucketACL return InvalidArgument for bad ID

lib/routes/routesUtils.js, tests/functional/aws-node-sdk/test/legacy/tests.js
* When the byte range is half the object size from a MPU, an error
is thrown by fs.ReadStream (`Error: start must be <= end`). This
causes a `NetworkingError: socket hang up` error in file backend.
This commit fixes that and modifies the test to ensure that the
range is handled properly.
=> BF: Fix off by one range

circle.yml, tests/functional/aws-node-sdk/test/support/config.js
Due to the large CI output, browsers crash when trying to open the CI and there is a lot of noise in the output.
This is EXTREMELY frustrating.
Here, I send the server logs to files in the artifacts and quiet AWS-SDK logs.
=> Redirect CI test output and quiet AWS SDK logs

tests/functional/aws-node-sdk/test/legacy/authV2QueryTests.js
Test is testing whether expiration time is too far
in the future.  With the public CI, 1 second is not
long enough to give the public CI time to make the call
and fail as expected (meaning pass the test) on some runs.
=> Extend expiration time in v2 query test.

tests/functional/boto/boto/setup.py, tests/functional/boto/boto/tests/test_boto.py
This will "unblock" the CI by fixing the linting error that came with flake8's pip package update.
Another option would be to set the version we install in the circle.yml, but would probably be easily out-of-sync with the developer's setup. As such I took the "fix-it" approach.
=> chore: Fix flake8 linting error following package upgrade

lib/api/bucketGet.js, tests/functional/s3curl/tests.js
=> COMPAT: AWS rejects invalid max-keys for listObjects

lib/api/bucketGet.js, tests/functional/s3curl/tests.js
Fixes #380
If url encoding is specified, the response object needs to include
an XML tag EncodingType with the value 'url'.
=> COMPAT: Handle url encoding in bucketGet API

lib/api/objectGet.js, tests/functional/aws-node-sdk/test/legacy/tests.js
Fixes #378
If `Range` parameter is given to getObject API, the 'Accept-Range'
header should be set to 'bytes' regardless whether or not the
given range is valid. Prior to this change, [this test](https://github.com/scality/S3/blob/master/tests/functional/aws-node-sdk/test/legacy/tests.js#L418)
would not return an object with an `AcceptRanges` key-value pair.
=> COMPAT: Set 'Accept-Range' header for all ranges in getObject API

lib/api/bucketGet.js, tests/functional/s3curl/tests.js
If an encoding type is given (i.e., it is not `undefined`)
and the encoding type is not 'url', then an `InvalidArgument`
error is returned with a message 'Invalid Encoding Method 
specified in Request'.
=> COMPAT: Return an error for an invalid encoding in getBucket API

lib/data/file/backend.js, lib/data/in_memory/backend.js, lib/data/wrapper.js, lib/routes.js, lib/utilities/healthcheckHandler.js, tests/functional/healthchecks/test/checkRoutes.js, tests/unit/healthchecks/healthcheckResponse.js
Creates route that will be called by load balancers, skips backends that don't have a `check` function. Includes the first implementation of a check for sproxyd for each backend option.
Depends on sproxydclient PR https://github.com/scality/sproxydclient/pull/92
=> Add backend healthcheck functionality

tests/functional/jaws/pom.xml
Pulling maven from the following no longer works: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
Need to specify http://repo1.maven.org/maven2 per https://maven.apache.org/guides/introduction/introduction-to-the-pom.html
=> FIX: maven source

lib/auth/streamingV4/V4Transform.js
Improve performance of streaming v4 auth by avoiding buffer.concat when know the buffer size.
=> PERF: Remove Buffer.concat for data chunks

lib/routes.js, lib/server.js, lib/utilities/healthcheckHandler.js
This change makes sure that all backends are working properly before listening for requests on the service port, allowing load balancers to try another server for write requests without introducing non-idempotent retries, because ECONNREFUSED is a clean failure.
=> Wait for positive backend healthchecks on startup

lib/auth/in_memory/vaultUtilities.js
The binary digest for the signing key make
s3 under node v6 to generate wrong signature.
This pull request fix that.
=> FIX: Signing key binary

lib/api/listMultipartUploads.js, lib/metadata/in_memory/getMultipartUploadListing.js, tests/functional/aws-node-sdk/lib/utility/bucket-util.js, tests/functional/aws-node-sdk/test/legacy/tests.js, tests/functional/aws-node-sdk/test/object/mpu.js
This commit fixes issues that were causing listMultipartUploads
to contain 'undefined' as XML content:
* `services.getMultipartUploadListing` in listMultipartUploads.js is
passing an `undefined` DisplayName for the owner of the MPU and
an `undefined` StorageClass for an upload. This results in the
following JSON response for the listMultipartUploads API,
respectively:
```javascript
"Owner": { "DisplayName": "undefined", ... }
"Uploads": [{ ... "StorageClass": "undefined", ... }]
```
* Changes in getMultipartUploadListing.js fixes the
issues stated in the above bullet point by retrieving the proper
values for the keys `DisplayName` and `StorageClass`
* For values that could be `undefined` in the listMultipartUploads
API, use empty XML elements if the value is, in fact, `undefined`
* Add …
=> COMPAT: Handle `undefined` values for listMultipartUploads API

Healthchecks.md, circle.yml, lib/Config.js, lib/RedisClient.js, lib/StatsClient.js, lib/routes.js, lib/routes/routeDELETE.js, lib/routes/routeGET.js, lib/routes/routeHEAD.js, lib/routes/routePUT.js, lib/utilities/healthcheckHandler.js, lib/utilities/statsReport500.js, package.json, tests/functional/config.json, tests/functional/healthchecks/test/checkRoutes.js
This commit introduces stats for healthcheck route. On a successful healthcheck, the response
includes the total number of requests received and the number of 500s occured over a sampling
duration. The current default for sampling duration is 30 seconds.
=> ft: add stats to healthcheck route

tests/functional/aws-node-sdk/lib/utility/getRange.c, tests/functional/aws-node-sdk/test/object/rangeTest.js
This PR refactors range tests by using files created with the executable file of getRange.c where each byte of the file is a hash of its offset. The C code is written by Flavien Lebarbe. The general approach for each test: 
1. Generate a hashed file of a certain number of bytes with the executable and put that file in a bucket. 
2. Use the getObject API to retrieve the byte range from the object in the bucket and write a file with the response body.
3. Check the file's bytes (the one written in step 2) with the getRange executable program.
3. Success!
=> TEST: Refactor range tests to use getRange.c

Dockerfile, DockerfileMem, conf/authdata.json, config.json, docker-entrypoint.sh
This PR adds an entrypoint that allows user to:
- Modify Docker user credentials
- Specify an host name 
- Log level
using [Docker environment variables](https://docs.docker.com/engine/reference/run/#/env-environment-variables).
**Docker command:**
` docker run -d --name s3server -p 8000:8000 -e HOST_NAME=new.host.com -e ACCESS_KEY=newAccessKey -e SECRET_KEY=newSecretKey scality/s3server`
If you want to try these changes, you will have to build an image from this branch 
`docker build ./ -t s3` and run the container.
=> DOCKER: using Environment Variables

tests/functional/healthchecks/test/checkRoutes.js
This commit adds a delay of 100ms to ensure that stats request is made
after the Redis calls are complete, otherwise it will result in a race
condition making the test fail.
=> fix: flaky healthcheck test

Dockerfile, DockerfileMem
I was happy to see that you made the Docker image lighter in 244a5f12cbc5fd3193d1a14a3b3be9ca160ec7b9.
I was able to reduce the image size even further.
Here are the commands I used to check the image size before and after each change:
docker build -f DockerfileMem -t scality/s3server:mem-latest .
docker save scality/s3server:mem-latest | pxz > 01.tar.xz && du -h 01.tar.xz
**master**
119M    01.tar.xz
**After 'rm -rf /var/lib/apt/lists/*'**
110M	01.tar.xz
**After 'npm cache clear':**
95M	01.tar.xz
=> Make Docker image even lighter

circle.yml, package.json, tester.js, tests/functional/aws-node-sdk/master.json, tests/functional/aws-node-sdk/package.json, tests/functional/s3cmd/master.json, tests/functional/s3cmd/package.json, tests/functional/s3curl/master.json, tests/functional/s3curl/package.json, wait_for_local_port.bash
This PR aims at enabling to patch the dependencies for the functional tests that are used in E2E testing (targeted rel/6.2 to have a wide dependency patcher support). 
This PR depends on #360 (included as a cherry-picked dropme commit).
It addresses issue #359, and does a bit of cleanup.
=> Regroup package.json dependencies into Project's package.json

lib/api/listMultipartUploads.js, lib/metadata/in_memory/getMultipartUploadListing.js, tests/functional/aws-node-sdk/test/object/mpu.js
Currently, the value of `MaxUploads` for listMultipartUpload API is
the number of MPU in a bucket. This is not the behavior of AWS. This
commit changes the API's behavior so the value of `MaxUploads` can be
specified by the user using the `MaxUploads` parameter. This commit also
returns the expected default of 1000 if no `MaxUploads` is defined.
If `MaxUploads` is defined as `0`, the behavior of AWS is to return an
empty `Uploads` array and set `IsTruncated` to `false`. This commit also
adds this expected behavior.
Currently, when using the file-backend, if a `Delimiter` parameter is
defined and it does not result in a `CommonPrefixes` array that is
greater than 0, `Delimiter` is set to `''`. This causes the XML response
to omit the `Delimeter` key. For compatibility with AWS, this commit …
=> COMPAT: Return expected response for `MaxUpload` and `Delimiter` params

lib/api/listParts.js, lib/services.js, tests/functional/aws-node-sdk/test/object/listParts.js, tests/unit/api/listParts.js
FIXES #445
The issue is related with the fact that in the [MarkerFilter function ](https://github.com/scality/S3/blob/d3ba43b87ce07a640ade2413f5f915e178a73dff/lib/metadata/in_memory/bucket_utilities.js#L1), a marker was never equals to any keys.  This is for the in memory implementation.  For the file backend and other backends, LevelDB also needs a padded part number to sort correctly.
=> BF: ListPart - when PartNumberMarker > 0 return no part

tests/functional/aws-node-sdk/test/object/listParts.js
Because using `allocUnsafe` the contents of the newly created Buffer are unknown and may contain sensitive data
=> FIX: Fill buffer with zeros

lib/data/file/backend.js, lib/data/in_memory/backend.js, lib/data/wrapper.js
The handling to check if the backend healthcheck function exists was done differently in vaultclient and bucketclient from sproxyd. This makes sproxyd follow the same format.
=> Make func check handling consistent across backends

lib/utils.js, tests/functional/aws-node-sdk/test/bucket/put.js
The bucketname check loosely checked if it matches an IP address, this
failed bucketnames which includes IP with prefixes. The commit adds a strict
check so that regex matches exactly an IP address.
fix #464
=> fix: allow bucket names with IP addresses in them

lib/api/api.js, lib/api/apiUtils/bucket/bucketShield.js, lib/api/apiUtils/bucket/bucketWebsite.js, lib/api/bucketPutWebsite.js, lib/metadata/BucketInfo.js, lib/metadata/ModelVersion.md, lib/metadata/WebsiteConfiguration.js, lib/routes/routePUT.js, lib/utilities/pushMetrics.js, tests/functional/aws-node-sdk/lib/utility/website-util.js, tests/functional/aws-node-sdk/test/bucket/putWebsite.js, tests/unit/api/bucketPutWebsite.js, tests/unit/bucket/BucketInfo.js, tests/unit/bucket/WebsiteConfiguration.js, tests/unit/helpers.js
Depends on
scality/Arsenal#196,
scality/utapi#67, &
scality/Integration#321
Call action for ?website query in routePUT
* Add putBucketWebsite to shielded actions
* Update BucketInfo modelVersion to 4: include website configuration info
* Parse and validate xml WebsiteConfiguration body
* Send API metrics to utapi & deliver success or err response
=> FT: Add putBucketWebsite to API

lib/api/apiUtils/object/storeObject.js, lib/api/objectPutPart.js, lib/services.js
Fixes refactoring part of #153
* Call `metadata.getBucket` directly and perform validation checks in the API.
* Remove calls to `services.metadataValidateAuthorization`, `services.metadataValidateMultipart`, and `services.getMPUBucket`.
* Remove `doStore` function and instead call `services.dataStore` and `services.metadataStorePart` directly in API.
* Remove extraneous code after the above changes.
=> FIX: Refactor objectPutPart API

constants.js, lib/api/bucketGet.js, tests/unit/api/bucketGet.js
Allow a bucket listing to return a max keys number
greater than actual keys returned to mirror AWS.
=> Restore max limit on listing

lib/routes/routesUtils.js, lib/utils.js
Translate x-amz headers on receipt and before sending out to handle translated characters.
=> Handle bad headers

config.json, lib/Config.js, lib/api/apiUtils/bucket/bucketCreation.js, lib/api/bucketPut.js, lib/metadata/BucketInfo.js, lib/metadata/ModelVersion.md, tests/functional/s3curl/tests.js, tests/unit/bucket/BucketInfo.js, tests/unit/bucket/bucketCreation.js
AWS does not return 409 for bucketAlreadyOwned
if bucket is in us-east-1 and request is to us-east-1.
This fixes https://github.com/scality/S3/issues/475
=> COMPAT: Mirror AWS err for bucketAlreadyOwned

lib/api/apiUtils/authorization/aclChecks.js, lib/api/apiUtils/bucket/bucketShield.js, lib/api/bucketGetVersioning.js, lib/api/bucketPutVersioning.js, lib/api/bucketPutWebsite.js, tests/unit/api/bucketACLauth.js
There is a similar group of bucket-level actions which are only permitted if user is the bucket owner or has granted permissions. This commit refactors acl checks to explicitly check whether an action belongs to this category and adds this requestType to bucketShield. For existing api actions, it affects bucketPutVersioning, bucketGetVersioning, and bucketPutWebsite.
=> REFACTOR: Add & use bucketOwnerAction requestType

lib/api/api.js, lib/api/bucketDeleteWebsite.js, lib/routes/routeDELETE.js, lib/utilities/pushMetrics.js, tests/functional/aws-node-sdk/test/bucket/deleteWebsite.js, tests/unit/api/bucketDeleteWebsite.js, tests/unit/api/deletedFlagBucket.js, tests/unit/api/transientBucket.js
Deletes a bucket's website configuration stored in metadata.
Depends on
scality/Arsenal#202,
scality/utapi#69,
scality/Integration#365, &
scality/S3#469
=> FT: Add deleteBucketWebsite to API

lib/metadata/BucketInfo.js
This was omitted in forward port from 6.3, despite updating ModelVersion.md document to describe Model Version 5 for the `websiteConfiguration` property.
=> CLEANUP: Update BucketInfo Model Version to 5

bin/list_metrics.js, lib/utapi/utilities.js
Refactors listing metrics to allow for account-level Utapi listing. We are accommodating the refactored methods to maintain support for the current way of listing bucket metrics. Hence we keep bin/list_bucket_metrics.js.
Depends on https://github.com/scality/utapi/pull/75.
=> FT: Add account level list metrics

lib/api/listParts.js, tests/functional/aws-node-sdk/test/object/listParts.js
List parts does not need tests for prefix, marker, next marker as they are string
hashes and not object keys which may have invalid xml characters.
fixes #519
=> fix: escape xml characters

tests/functional/aws-node-sdk/test/bucket/get.js
NextMarker is only available when Delimiter is specified in the params
=> tests: fix incorrect object listing tests

lib/api/api.js, lib/api/apiUtils/object/corsResponse.js, lib/api/corsPreflight.js, lib/routes.js, lib/routes/routeOPTIONS.js, tests/functional/aws-node-sdk/lib/utility/cors-util.js, tests/functional/aws-node-sdk/test/object/corsPreflight.js
Depends on scality/S3#507 (deleteBucketCors and its prerequisite putBucketCors)
Reference: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTOPTIONSobject.html
Thanks @nicolas2bert for the bulk of the tests!
=> FT: Add OPTIONS route for CORS response

lib/api/objectPutPart.js, tests/unit/api/multipartUpload.js
Fix #153
Update Utapi metrics on `objectPutPart` overwrites and remove orphaned data on overwrite.
See associated PRs: 
https://github.com/scality/Integration/pull/384
https://github.com/scality/utapi/pull/71
=> FIX: Handle `objectPutPart` overwrites

config.json, lib/Config.js, lib/server.js
Adds a new field to the config file that allows users to explicitly set a host:port for the s3 server to listen on.
=> Add listenOn field to config

lib/routes/routePOST.js
Fix #551
Pass `errors.NotImplemented` (err code 501)
instead of `errors.InternalError` (err code 500)
=> BF: Update error code in routePOST

tests/functional/aws-node-sdk/test/object/compluteMpu.js
Needed to update this test now that MAX_POST_SIZE for POST route was updated in https://github.com/scality/S3/pull/560 to 1 MB.
=> FIX: update completempu test for 1 MB limit

lib/server.js
This allows seamless exits/restarts where already-connected clients
won't get any errors for in-flight requests.
Fix #550
=> FIX: Exit server when connections are drained

lib/Config.js
Adds a `component` property to the Utapi configuration. 
When introducing service-level metrics, including this property will allow the Utapi client to determine which service is pushing the metrics (the configuration is passed in the instantiation of `UtapiClient`).
=> FT: Add component to Utapi config

lib/server.js
Only set one timeout to check worker killed.
Check that worker.suicide not already
set before killing.
Should help prevent seeing errors like those described here: https://github.com/scality/S3/issues/546
=> FIX: Kill worker less zealously

DESIGN.md
Wasn't sure to add spaces or not since there are examples of both:
```
- PutBucketACL
- GetBucketACL
```
```
- Put Bucket Website
- Get Bucket Website
- Delete Bucket Website
```
Happy to modify either way.
=> FT: Add bucketCors actions to DESIGN.md

tests/functional/aws-node-sdk/test/object/bigMpu.js
https://github.com/scality/Integration/issues/449
This test has been flaky on end-to-end CI tests recently. Disabling retries prevented InvalidPart errors but we have still encountered SocketHangUp errors since. This aims to prevent those errors by increasing SDK timeout config for this test from default of 2 minutes to 5 minutes.
=> FIX: large mpu test socket hangup

lib/api/multipartDelete.js
Get sum of part sizes from existing part objects to pass to utapiClient.
=> FIX: Include part size sum in Utapi object

lib/Config.js
This patch removes the check of the IP's format, since we want to be able to use FQDNs instead.
Related to our ongoing multi-ports fixes.
=> listenOn: Disable IP parsing to allow the usage of FQDNs

lib/api/api.js, lib/api/websiteGet.js, lib/api/websiteHead.js, package.json, tests/functional/aws-node-sdk/lib/utility/website-util.js, tests/functional/aws-node-sdk/test/object/websiteGet.js, tests/functional/aws-node-sdk/test/object/websiteGetWithACL.js, tests/functional/aws-node-sdk/test/object/websiteHead.js, tests/functional/aws-node-sdk/test/object/websiteHeadWithACL.js, tests/functional/aws-node-sdk/test/object/websiteRuleMixing.js, tests/functional/raw-node/utils/makeRequest.js
FIXES #553
Also includes commit for refactoring website tests and clean-up in preparation for adding auth credentials to the website test requests. Zombie was a neat tool for visiting websites as if in a browser, but since it added unnecessary wait time to the redirect tests and we can check what we need in the response using the node `http`/`https` request module, I removed it.
=> FIX: remove auth credential check from websiteHead/Get

lib/server.js, tests/functional/aws-node-sdk/test/object/deleteObject.js
In Node6 
- `worker.suicide` is deprecated. Using `worker.exitedAfterDisconnect` instead.
- `new Buffer(size)` is deprecated. Using `Buffer.allocUnsafe()` instead.
=> node6: worker.suicide and new Buffer() deprecated

lib/Config.js, tests/unit/testConfigs/sproxydAssert.js
Previously, the parsing logic assumed that sproxyd would have either a bootstrap list or a chordCos value. This PR allows for both to be used
=> Fix logic in parsing of sproxyd config and update tests

lib/api/apiUtils/bucket/bucketCreation.js, lib/api/apiUtils/bucket/bucketDeletion.js, lib/api/completeMultipartUpload.js, lib/api/multiObjectDelete.js, lib/api/objectPutCopyPart.js, lib/api/objectPutPart.js, lib/api/websiteGet.js, lib/api/websiteHead.js, lib/metadata/acl.js, lib/metadata/bucketclient/backend.js, lib/metadata/bucketfile/backend.js, lib/metadata/in_memory/backend.js, lib/metadata/wrapper.js, lib/services.js, tests/unit/api/deletedFlagBucket.js, tests/unit/api/objectPut.js, tests/unit/api/objectPutACL.js, tests/unit/api/transientBucket.js, tests/unit/bucket/bucket_mem_api.js
This PR is in preparation for refactoring the S3 api methods for versioning.
It should be able to be merged immediately.
- reorder metadata wrapper params to precede callback
- pass callback params directly from bucketclient (when versioning is merged in MD, this will include versionId for affected methods)
=> rf: metadata params for versioning S3C-44

lib/api/apiUtils/bucket/bucketDeletion.js, tests/unit/api/bucketDelete.js
Only block the deletion of a bucket if there is an
overview object in the mpu shadow bucket. If there are
orphan part objects, proceed with the deletion.
=> FIX: Limit bucket deletion blocking for mpu

circle.yml, tests/functional/fog/tests.rb
Prevent wait in CircleCI that causes a timeout
```
[...]
fog's executable "fog" conflicts with fog-digitalocean
Overwrite the executable? [yN]  
command gem install fog took more than 10 minutes since last output
```
Currently all fog providers are getting separated into metagems to lower the load time and dependency count. Thus we should be using `fog-aws` instead of requiring the full fog collection to avoid unnecessary dependencies. (See Dependency Notice section of https://github.com/fog/fog.)
=> DEV: Use fog-aws metagem

lib/utapi/utilities.js
If a user is performing an action, include the userId in the object to track user-level metrics.
=> FT: Push user-level utapi metrics

package.json
Since aws sdk new version introduce a format change in some returns
(at least Content-Length, previously a string, now a number). An
amount of tests are currently failing. Fixing to the previous aws
version for now until we change tests / aws sdk rollback on this.
Version introducing the bug https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#2290
=> FIX: Aws sdk version

lib/data/file/backend.js
This should fix corruption issue when shutting down the power, by
forcing fsync() to be called after all user-space buffers have been
flushed to the OS.
Credits to @RemiCardona for spotting the root cause of the issue
fixes #662
=> Flush write stream buffers before fsync()

lib/api/initiateMultipartUpload.js, tests/unit/api/multipartUpload.js
I am unable to add a test for the added error handler without a lot of refactoring so I am just making the fix for now. In a separate commit, I added an error handling initiate mpu test to test an error that is returned earlier but was not tested.
=> S3 c 182/fix/missing error handler

lib/Config.js, lib/data/locationConstraintParser.js, locationConfig.json, tests/unit/testConfigs/cosParse.js, tests/unit/testConfigs/sproxydAssert.js
Gives user ability to set custom sproxyd path in bootstrap array and fixes chordCos parsing.
Goes with https://github.com/scality/sproxydclient/pull/118
=> Make sproxyd path customizable

lib/utapi/utilities.js
Query params sent to the arsenal auth method currently only handle bucket-level metrics. Since the listing binary supports account-level metrics, we also need to be able to send the correct path for account-level listings. This also prepares the route for remaining metric levels: to be introduced in https://github.com/scality/S3/pull/536
=> FIX: Handle account-level metrics listing

lib/utapi/utilities.js
Adds the option to list recent metrics using the Utapi route with action `ListRecentMetrics`. This will return the latest metrics of between `Date.now()` and the second most recent fifteen minute interval (e.g., if it is 6:31 when the request is made, then list metrics starting from 6:15). 
If `start` or `end` options are provided along with the `recent` option, they will be ignored and metrics of the "recent" time range will be returned.
Depends on https://github.com/scality/utapi/pull/114.
=> FT: Add recent metrics listing option

lib/api/apiUtils/object/validRangeOnEmptyFile.js, lib/api/objectGet.js, tests/functional/aws-node-sdk/test/legacy/tests.js, tests/unit/helpers.js, tests/unit/utils/validateRange.js
FIXES: #660 
AWS returns the empty object if there is an invalid range but sends an invalidRange error if the range is valid on an empty object
=> BF: get empty object with valid/invalid range

lib/api/apiUtils/authorization/prepareRequestContexts.js
S3C-156
For requests that have version id's use correct "action" when sending requestContext to vault.
=> ft: proper versioning action for Vault

lib/data/wrapper.js, locationConfig.json, tests/unit/api/objectGet.js
If a server was started with multiple backends after having put an object on a server started with file backend, the object would be unretrievable. This PR fixes that
=> bf/Handle dataFile and datatMem backend names

lib/metadata/bucketfile/backend.js, tests/unit/metadata/bucketfile/backend.js
Fix the missed out check in #651 for the filtering results of listing in bucketfile (should check for numeric values instead of boolean).
=> fix: check for numeric filtering results instead of boolean

lib/api/apiUtils/object/createAndStoreObject.js, lib/api/apiUtils/object/parseCopySource.js, lib/api/apiUtils/object/versioning.js, lib/api/bucketGet.js, lib/api/completeMultipartUpload.js, lib/api/multiObjectDelete.js, lib/api/objectCopy.js, lib/api/objectDelete.js, lib/api/objectGet.js, lib/api/objectGetACL.js, lib/api/objectHead.js, lib/api/objectPut.js, lib/api/objectPutACL.js, lib/api/objectPutCopyPart.js, tests/functional/aws-node-sdk/lib/utility/versioning-util.js, tests/functional/aws-node-sdk/test/object/completeMPU.js, tests/functional/aws-node-sdk/test/versioning/listObjectMasterVersions.js, tests/functional/aws-node-sdk/test/versioning/listObjectVersions.js, tests/functional/aws-node-sdk/test/versioning/multiObjectDelete.js, tests/functional/aws-node-sdk/test/versioning/objectACL.js, tests/functional/aws-node-sdk/test/versioning/objectCopy.js, tests/functional/aws-node-sdk/test/versioning/objectDelete.js, tests/functional/aws-node-sdk/test/versioning/objectHead.js, tests/functional/aws-node-sdk/test/versioning/objectPut.js, tests/functional/aws-node-sdk/test/versioning/objectPutCopyPart.js
Dependent on https://github.com/scality/Arsenal/pull/242
Switched to just encoding the version ids, and hex instead of base64 to simplify authentication checks.
Functional tests were changed just to test with both v2 and v4, not just v4. The large diffs are mostly due to indentation level.
=> rf: change encoding of version ids [S3C-184]

lib/auth/vault.js
Depends on https://github.com/scality/vaultclient/pull/136.
Since vaultclient creates its own request Logger using the requestUID, we just pass the requestUID. We also allow the log and dump level to be configured based on the `log` field of Config.js.
=> FT: Pass requestUID to vaultclient

config.json, init.js, lib/Config.js, lib/metadata/bucketfile/backend.js, mdserver.js, package.json, tests/unit/metadata/bucketfile/backend.js
The changes allow bucketfile to use a new API in Arsenal to
communicate with a remote leveldb database, containing sublevels for
bucket storage. Metadata is still stored on a local levelDB server,
but it should now be easy to move the storage logic in a new daemon
running on a remote server, and it should be robust.
Instead of relying on the existing implementation of multilevel, it
uses client/server wrappers around a new level-net communication
protocol and API in Arsenal based on socket.io to exchange messages.
It shall be compatible with the existing metadata since it still uses
the core sublevel module for the storage logic, only the RPC procotol
has changed.
Test done:
- put a few 100s of files in different S3 subdirectories
- list directories and subdirectories
- get/delete files
- …
=> S3C-35 Refactoring of bucketfile

lib/api/bucketDelete.js, lib/api/bucketGet.js, lib/api/bucketGetACL.js, lib/api/bucketGetVersioning.js, lib/api/bucketHead.js, lib/api/bucketPutACL.js, lib/api/bucketPutVersioning.js, lib/api/completeMultipartUpload.js, lib/api/initiateMultipartUpload.js, lib/api/listMultipartUploads.js, lib/api/listParts.js, lib/api/multipartDelete.js, lib/api/objectCopy.js, lib/api/objectPutCopyPart.js, lib/metadata/metadataUtils.js, lib/services.js
Versioning PR introduced new metadata validation function called metadataValidateBucketAndObj, so the old metadataValidateAuthorization function is no longer needed.
=> CLEANUP: Remove obsolete metadataValidateAuthorization func

lib/api/multiObjectDelete.js, tests/functional/aws-node-sdk/test/versioning/multiObjectDelete.js
Fixing ceph test: 
`ERROR: s3tests.functional.test_s3.test_versioning_multi_object_delete_with_marker_create`
`DeleteMarkerVersionId` should be a versionId not a boolean. 
6. Also check that multi-object delete has ‘isDeleteMarker’ in result in both cases deleting delete marker and new delete marker (according to AWS)
=> FIX: returning correct DeleteMarkerVersionId when deleteObjects

lib/api/bucketPut.js, tests/multipleBackend/objectPutCopyPart.js, tests/multipleBackend/objectPutPart.js, tests/unit/api/bucketPut.js
We should always explicitly set a location constraint on a bucket if data backend equals 'multiple'.
=> S3C-287 FIX: Always set bucket location

lib/api/apiUtils/object/createAndStoreObject.js, lib/services.js, tests/unit/api/deleteMarker.js, tests/unit/api/objectDelete.js
@jonathan-gramain noticed we did not reset the content length for multi-object delete requests when creating delete markers, meaning the delete marker stores content-length with the length of the xml, which is incorrect and causes the request to hang at least for file backend. It would likely also pose an issue for accurately tracking bytes created in Utapi.
=> fix: delete marker creation / md [S3C-184]

lib/api/apiUtils/object/createAndStoreObject.js, lib/api/apiUtils/object/versioning.js, lib/api/completeMultipartUpload.js, lib/api/objectCopy.js, tests/unit/api/multipartUpload.js, tests/unit/api/objectCopy.js, tests/unit/api/objectPut.js, tests/unit/helpers.js
Depends on scality/S3#698
Normally we overwrite and clean data when creating a new version when versioning is suspended 
and the latest version is a null version. However, we must also take care to delete the data when overwriting a null version that is not the latest version.
=> FIX: ensure null ver data is deleted on overwrite [S3C-184]

lib/api/objectGetACL.js, lib/api/objectPutACL.js, tests/functional/aws-node-sdk/test/versioning/objectACL.js
We were not checking for delete markers when responding to put and get acl requests.
=> fix: add objAcl checks for delete marker [S3C-184]

docs/listing.md, lib/api/bucketGet.js, lib/metadata/bucketfile/backend.js, lib/metadata/in_memory/backend.js, lib/metadata/metadataUtils.js, lib/metadata/wrapper.js, tests/functional/aws-node-sdk/test/versioning/listObjectMasterVersions.js, tests/functional/aws-node-sdk/test/versioning/listObjectVersions.js
No longer use 'Basic' listing type.
Move JSON parsing for 'DelimiterVersions' to metadata wrapper to be consistent with what we do for other listing types.
Add some more assertions to listing tests.
Note that it seems we still use 'Delimiter' listing type for listing buckets and for internal bucket listing, such as listing objects inside a mpuBucket.
=> rf: clean up listing types, parsing [S3C-184]

constants.js, lib/api/apiUtils/object/setUpCopyLocator.js, lib/api/objectPutPart.js, tests/functional/aws-node-sdk/test/object/copyPart.js
=> Fix: EntityTooLarge error for put part

lib/api/apiUtils/object/tagging.js, tests/functional/aws-node-sdk/lib/utility/tagging.js, tests/functional/aws-node-sdk/test/object/putObjTagging.js
For `putObjectTagging` - the tag's value can be an empty string. 
However - tag's key can not be empty
=> FIX: put object tag with empty value

circle.yml, lib/auth/streamingV4/V4Transform.js, tests/functional/fog/tests.rb, tests/functional/jaws/src/test/java/com/scality/StreamV4AuthTest.java, tests/unit/auth/V4Transform.js
In streaming v4 auth, the last piece is indicated by:
0;chunk-signature=whateversig\r\n\r\n
We were only expecting:
0;chunk-signature=whateversig\r\n
So in the infrequent event when the final '\r\n' was in a separate chunk in the node transform stream, we were doing an unnecessary authentication step which was resulting in a signature mismatch error.
This PR addresses that problem, adds additional logs and cherry-picks a prior streaming v4 refactor that was applied in 6.4
=> Fix: Streaming v4 auth extra chunk

lib/api/multiObjectDelete.js, lib/api/objectDelete.js, lib/routes/routeDELETE.js, tests/functional/aws-node-sdk/test/versioning/multiObjectDelete.js, tests/functional/aws-node-sdk/test/versioning/objectDelete.js
- tests to confirm we do not create delete markers for deleting specific versions
- make sure version ID is sent back for requests trying to delete non-existing version
=> fix: return versionId when delete non-exist ver [S3C-368]

tests/functional/aws-node-sdk/lib/utility/versioning-util.js, tests/functional/aws-node-sdk/test/versioning/objectACL.js, tests/functional/aws-node-sdk/test/versioning/objectDeleteTagging.js, tests/functional/aws-node-sdk/test/versioning/objectPutTagging.js
**AWS compatibility**
AWS does not create version:
- putting ACL on a version-enabled bucket where no version id is specified
- putting object tags on a version-enabled bucket where no version id is specified
- deleting object tags on a version-enabled bucket where no version id is specified
=> TEST: version non-specified (tag and acl)

lib/api/api.js, lib/api/apiUtils/authorization/prepareRequestContexts.js, lib/api/objectGet.js, lib/utilities/collectResponseHeaders.js, tests/functional/aws-node-sdk/test/object/get.js, tests/functional/aws-node-sdk/test/versioning/objectGet.js, tests/unit/api/deletedFlagBucket.js, tests/unit/api/objectDelete.js, tests/unit/api/objectGet.js, tests/unit/api/transientBucket.js
E2E passed with https://github.com/scality/Integration/pull/523
Testing getObject with tagging:
- if `s3:GetObject` and `s3:GetObjectTagging` permissions : getObject return the header: `x-amz-tagging-count` that provides the count of number of tags associated with the object.
- if `s3:GetObjectVersion` and `s3:GetObjectVersionTagging` permissions : getObject with versioning return the header: `x-amz-tagging-count`.
=> FT: getObject with tagging

lib/api/apiUtils/authorization/prepareRequestContexts.js
To specify tags on an object, the requester must have `s3:PutObjectTagging` included in the list of permitted actions in their IAM policy.
=> FX: putObject with tag set policy

lib/routes/routesUtils.js
When getting a large object, we are experiencing memory issues. This is a patch to prevent the issues from occurring when an object was put without MPU.
=> Patch: Bypass double buffering for 1 location

DOCKER.md, docker-entrypoint.sh
Docker environment variable to run Scality S3 server with multiple data backends.
=> DOCKER: add env var for multiple data backends

lib/routes/routesUtils.js, lib/utilities/retrieveData.js, package.json
S3C-429
Prevent memory problems by no longer double buffering.
(cherry picked from commit 1ae15540d5e29bebce7244252599eea44288826f
with modifications to resolve conflicts)
=> FIX: Only stream from one data location at a time.

lib/api/apiUtils/authorization/prepareRequestContexts.js
If `x-amz-grant-read, x-amz-grant-read-acp, and x-amz-grant-write-acp, x-amz-grant-full-control`
or `x-amz-acl` headers are used to change the object ACLs to something other than the default, the requester must have `s3:PutObjectAcl` included in the list of permitted actions in their AWS Identity and Access Management (IAM) policy. 
Integration tests: https://github.com/scality/Integration/pull/531
=> S3C-413 put object ACL with s3:PutObjectAcl permission

lib/api/apiUtils/bucket/models/ReplicationConfiguration.js, tests/unit/api/bucketPutReplication.js
The ID property of a rule in the replication configuration is optional. However if a rule ID is omitted, we should generate a unique ID to store with the bucket replication metadata. That ID is then associated with the rule and should be accessible with the bucketGetReplication API.
=> FT: Create replication rule ID if not provided

lib/api/apiUtils/authorization/prepareRequestContexts.js
If `x-amz-grant-read, x-amz-grant-read-acp, and x-amz-grant-write-acp, x-amz-grant-full-control`
or `x-amz-acl` headers are used to change the object ACLs to something other than the default, the requester must have `s3:PutObjectAcl` included in the list of permitted actions in their AWS Identity and Access Management (IAM) policy. 
Integration tests: https://github.com/scality/Integration/pull/532
=> S3C-413 copy object ACL with s3:PutObjectAcl permission

constants.js, lib/api/apiUtils/object/createAndStoreObject.js, lib/api/initiateMultipartUpload.js, lib/api/objectCopy.js, lib/services.js, lib/utils.js, tests/functional/aws-node-sdk/lib/utility/genMaxSizeMetaHeaders.js, tests/functional/aws-node-sdk/test/object/initiateMPU.js, tests/functional/aws-node-sdk/test/object/objectCopy.js, tests/functional/aws-node-sdk/test/object/put.js
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html
AWS limits user-provided metadata to 2 KB. Now that we are implementing AWS and other backends, we should be consistent in the amount of user metadata we allow during puts.
=> ft: limit user metadata to 2 KB

README.md, lib/Config.js, lib/api/apiUtils/object/BackendInfo.js, lib/api/bucketPut.js, tests/functional/aws-node-sdk/test/multipleBackend/unknownEndpoint.js, tests/unit/api/bucketPut.js, tests/unit/api/multipartUpload.js, tests/unit/multipleBackend/BackendInfo.js, tests/unit/testConfigs/locConstraintAssert.js
1) If have object level location constraint
or bucket level location constraint allow
operation to continue even if restEndpoint is
not in config.
2) Set bucket location to us-east-1 if no location provided and no default for endpoint.
=> FIX: Allow operation if have valid loc

lib/api/apiUtils/object/createAndStoreObject.js, lib/api/apiUtils/object/versioning.js, lib/api/completeMultipartUpload.js, lib/api/objectCopy.js, tests/functional/aws-node-sdk/lib/utility/versioning-util.js, tests/functional/aws-node-sdk/test/versioning/objectACL.js, tests/functional/aws-node-sdk/test/versioning/objectDeleteTagging.js, tests/functional/aws-node-sdk/test/versioning/objectPut.js, tests/functional/aws-node-sdk/test/versioning/objectPutTagging.js
We identified a bug where we overwrite just the master null version when we have the same null version stored in master and a separate version, resulting in two null versions with different versionIds.
That situation may arise when putting object tags or acls on an existing master null version (using metadata PUT option `versionId=<version id of master version>` will both overwrite the master version + create new version with that versionId), for example, and then putting a new null version.
The solution settled upon is to do a separate clean-up delete call to delete the existing null version(s) before putting a new null version.
As @jonathan-gramain noted in a previous versioning PR, the versioningPreprocessing function was getting a bit long and nested and due for a refactor. Review by …
=> fix: clean up existing master null version before overwrite [S3C-444]

lib/data/locationConstraintParser.js
This is a new option in scality/sproxydclient that explicitly enables
immutable optims, because they are now disabled by default it's now
necessary to provide the option.
Goes along with PR https://github.com/scality/sproxydclient/pull/119
=> bf: immutable optim option on S3 sproxyd client

lib/Config.js, tests/unit/testConfigs/cosParse.js, tests/unit/testConfigs/sproxydAssert.js
When using the scality sproxyd storage, the chordCos should be a decimal integer smaller than 7 (bigger number are erasure coding and not replication.
Currently the chordCos is supposed to be a 2 hexadecimal digits string. This PR changes that.
=> BF S3C-531 chordChos must be 1 digit string smaller than 7

Dockerfile, docker-entrypoint.sh, docs/DOCKER.rst
This change allows changing more configuration options through environment variables in the `docker-entrypoint.sh` script.
The generated image is testable at `scality/s3server:with-jq`
The primary motivation is to avoid having to generate and distribute configuration files to dynamically scheduled container environments such as swarm.
=> New docker envionment variables

lib/server.js, lib/utilities/healthcheckHandler.js, lib/utilities/internalHandlers.js
Every url starting with '/_/' is now routed through a registered internal service handler in the routing code, instead of being specifically checked for a particular service. This will be useful to integrate backbeat routes properly in the next step.
Dependency on Arsenal PR https://github.com/scality/Arsenal/pull/274
=> cleanup: generalize internal routes handling

lib/api/apiUtils/object/createAndStoreObject.js, lib/api/apiUtils/object/replication.js, lib/api/objectDeleteTagging.js, lib/api/objectPutTagging.js, lib/metadata/acl.js, lib/metadata/models/object/ObjectMD.js, lib/services.js, tests/unit/api/objectReplicationMD.js, tests/unit/metadata/models/object.js
Add property `replicationInfo` to an object's metadata. Set the values conditionally for Backbeat to know which objects need to be replicated and whether to replicate the object data and/or metadata.
=> FT: Add replication information to object MD

constants.js, tests/unit/api/multipartUpload.js
The constant was accidentally deleted when extracting routes to Arsenal, causing the mpu bucket prefix to default to "undefined". Thanks to @bennettbuchanan for noticing the bug.
=> fix: missing mpu bucket prefix

tests/functional/aws-node-sdk/test/multipleBackend/get.js, tests/functional/aws-node-sdk/test/multipleBackend/put.js, tests/functional/aws-node-sdk/test/support/awsConfig.js, tests/multipleBackend/multipartUpload.js, tests/multipleBackend/objectPutPart.js
Allows multiple backend tests to be run with credential profile specified in locationConfig, instead of defaulting to 'default'
=> Fix AWS creds in testing

lib/Config.js, lib/api/apiUtils/bucket/models/ReplicationConfiguration.js
Allow including a custom array of replicationEndpoints in the `config.json`, any of which would be considered valid when putting the replicationConfiguration.
=> FT: Add configurable replication storageClass to objectMD

docker-entrypoint.sh, docs/DOCKER.rst
Using Subject Alternative Names (SAN) to specify both host and path style host names.
=> DOCKER: SSL for host and path style

lib/routes/routeBackbeat.js, tests/functional/raw-node/test/routes/routeBackbeat.js
ensure x-scal-canonical-id and content-md5 headers are provided in the `PUT .../data` backbeat route.
=> [backbeat] bf: sanity check on header presence

lib/Config.js
Small suggestion to avoid requiring the
conf/authdata.json file if custom credentials have
been set as container environment variables.
=> REFACTOR: do not require auth file if env variables are set

lib/data/external/AwsClient.js, tests/functional/aws-node-sdk/test/multipleBackend/put.js
Changes encryption type used on AWS backend to 'AES256' to match Scality S3 encryption type.
=> FIX: change AWS encryption type

lib/api/objectCopy.js, lib/data/external/AwsClient.js, lib/data/wrapper.js, tests/functional/aws-node-sdk/test/multipleBackend/objectCopy.js
Adds tests for objectCopy API with AWS backend. ~~Nothing had to be added to the API itself, but~~ a minor change was included because it directly impacted the testing. This is adding an error return on a GET call to AWS.
New features include 0-byte object support and copying objects across backends while retaining all other metadata.
=> Add tests for AWS object copy

config.json, docs/GETTING_STARTED.rst, lib/Config.js, locationConfig.json, package.json, tests/functional/aws-node-sdk/test/bucket/getLocation.js, tests/functional/aws-node-sdk/test/multipleBackend/put/put.js, tests/functional/s3cmd/tests.js, tests/functional/s3curl/tests.js, tests/locationConfigTests.json, tests/multipleBackend/multipartUpload.js
Separating the locationConfig for testing will make
it easier for users to start s3 server since they will
not have to deal with configuring Azure or AWS backends.
=> RF: Use separate locationConfig.json for testing

lib/api/objectCopy.js, lib/api/objectGet.js, lib/api/objectPutCopyPart.js, lib/data/external/AzureClient.js, lib/data/wrapper.js, tests/functional/aws-node-sdk/test/multipleBackend/get/get.js, tests/functional/aws-node-sdk/test/multipleBackend/get/getAzure.js, tests/functional/aws-node-sdk/test/multipleBackend/put/putAzure.js, tests/functional/aws-node-sdk/test/multipleBackend/utils.js, tests/unit/utils/responseStreamData.js
=> FT: AZURE GET

config.json, lib/Config.js, lib/data/wrapper.js, lib/kms/wrapper.js, lib/metadata/wrapper.js, package.json
This commit introduces the CDMI client data backend. A CDMI client
metadata backend will be added but for now, for testing purpose, when
the CDMI data backend is used, the metadata one is forced to be the file
one.
=> FT: add CMDI data backend

lib/api/apiUtils/object/createAndStoreObject.js, lib/api/apiUtils/object/storeObject.js, lib/api/completeMultipartUpload.js, lib/api/objectCopy.js, lib/api/objectPutCopyPart.js, lib/data/wrapper.js, tests/unit/api/objectGet.js, tests/unit/api/objectReplicationMD.js
Each element in the location array contains the ETag of its part.
the Etag is prefixed by the part number followed by a colon (```:```),
this permit to recursively track the origin of the parts in the case of a
multi part object built from multipart object put by copy.
=> implement dataStoreETag

lib/api/objectGet.js, tests/functional/aws-node-sdk/test/object/get.js
For a `getObject` request with a `PartNumber` param specified, we want to return the part's size as content length, and not the entire object's size.
=> COMPAT: Set part size as content-length

lib/api/objectGet.js, tests/functional/aws-node-sdk/test/object/get.js
When getting an object's part that was originally copied from an MPU, we need to dynamically search the `objMD.location` array to retrieve all locations that comprise the object part. 
We then use those locations to calculate the byte range which defines the part, return those bytes as the body and set the body size as the content-length.
✅  Tested with `AWS_ON_AIR=true`.
=> FIX: Get obj part when originally copied from MPU

lib/Config.js, lib/RedisClient.js, lib/routes.js
This commit takes the optional Redis password defined in the config and
propagates the config to localCache and Utapi.
=> ft: propogate redis password from config

lib/data/external/AwsClient.js, lib/data/external/AzureClient.js, lib/data/external/utils.js, tests/multipleBackend/multipartUpload.js
This PR includes for all of the Azure and AWS errors a "customizeDescription" so the user will instantly see the AWS/Azure error without having to look in the logs.
=> FT: add AWS/Azure customize error description

lib/Config.js
This commit updates the replication configuration format that gets
written to config.json. This format updates the properties from
name/endpoint to site/servers.
=> fix: update replication configuration format

lib/routes/routeBackbeat.js, tests/functional/raw-node/test/routes/routeBackbeat.js
This commit updates Backbeat routes format to gain flexibility on
the namespace.
=> ft: update Backbeat routes format

docker-entrypoint.sh
Fixes #863
Our default locationConfig no longer
needs to be modified to remove aws-test
since we now have a separate testing config.
=> FIX: Remove mod of locationConfig

lib/api/apiUtils/object/storeObject.js, tests/unit/api/objectPut.js
batchDelete expects the first param to be an array, but was being passed an object, which caused misleading orphan keys to not be deleted if the completedHash did not match.
Addresses JIRA S3C-709
=> Fix batch delete param

lib/routes/routeBackbeat.js, tests/functional/raw-node/test/routes/routeBackbeat.js, tests/functional/raw-node/utils/makeRequest.js
URIs received were not decoded at all in backbeat /data and /metadata
routes, so the object key was keeping the encoded characters
as-is. Then the key was applied a second URL encoding pass in the
target URL, leading to the object being replicated with a different
object key.
Fix by applying the same decoding than in S3 server to the original
URL received, with '+' replaced by ' ' prior to decoding
percent-encoded characters.
=> bf: decode URI in backbeat routes

docs/CLIENTS.rst
Even though v3 AWS SDK for PHP advertises it forces path-style
requests, it doesn't seem to (see http://forum.scality.com/t/issues-when-using-aws-sdk/127 ).
The new PHP template client features the "use_path_style_endpoint" set to true.
=> DOC: recommend forcing path-style AWS SDK PHP

lib/routes/routeBackbeat.js, tests/functional/raw-node/test/routes/routeBackbeat.js
Both data and metadata routes now return InvalidBucketState (as HTTP 409)
if bucket versioning is not enabled, to prevent various issues linked with
putting versions on a non-versioned bucket.
=> bf: refuse backbeat PUT if bucket is not versioned

lib/api/apiUtils/object/createAndStoreObject.js, lib/api/initiateMultipartUpload.js, lib/api/objectCopy.js, tests/functional/aws-node-sdk/test/multipleBackend/objectCopy.js, tests/functional/aws-node-sdk/test/multipleBackend/put/put.js, tests/functional/aws-node-sdk/test/multipleBackend/put/putAzure.js, tests/multipleBackend/multipartUpload.js
This PR returns error `NotImplemented` when putting a version to external data backend (ie AWS/AZURE)
=> FIX: return NotImplemented put version to external data

lib/metadata/bucketfile/backend.js, lib/metadata/wrapper.js, lib/utilities/reportHandler.js, tests/functional/report/checkRoutes.js
This change adds object, bucket and version counts to the report handler. Only implemented for bucketfile, which counts by inspecting all keys in the root DB.
=> Include bucket, object and version counts in reports

docs/ARCHITECTURE.rst, lib/Config.js, lib/data/external/AwsClient.js, lib/data/locationConstraintParser.js, lib/data/multipleBackendGateway.js, package.json, tests/functional/aws-node-sdk/test/multipleBackend/objectCopy.js, tests/functional/aws-node-sdk/test/multipleBackend/objectTagging.js, tests/functional/aws-node-sdk/test/multipleBackend/put/put.js, tests/locationConfigTests.json, tests/multipleBackend/backendHealthcheckResponse.js
In s3server we have bucket level encryption. 
AWS S3 has object level encryption. 
When we did the AWS backend on s3server, we decided to rely on AWS S3's object level encryption (instead of our own) so that encrypted objects would be readable if accessed directly from AWS S3. Now that we are bringing Azure into the picture, this gets complicated since Azure encryption is at the account level and s3server will not be messing with the account level settings.  
To make things consistent and to best carry-out the intent of users:
1) If a user creates an encrypted bucket, we always do the encryption on a put to this bucket (even if going to the azure or aws backends).
2) When setting up a locationConfig entry for the aws backend, we will allow them to set an option of "serverSideEncryption: …
=> FX: external backend ENCRYPTION

lib/Config.js, lib/auth/vault.js, tests/unit/Config.js
This allows dynamically updating the accounts portion of the in-memory auth backend data, by calling `config.setAuthDataAccounts(accounts)` with an account list as defined in conf/authdata.json.
=> FT: Allow updating account data on the fly

tests/functional/aws-node-sdk/test/object/get.js
Use md5 for body comparison in tests instead of comparing Buffers.
=> FIX: Use md5 for body comparison

tests/functional/aws-node-sdk/test/multipleBackend/listParts/azureListParts.js
Adds listParts API for Azure data backend. No calls actually need to be made to Azure since the part metadata is stored in Scality S3, so only tests included.
=> ft: azure list parts

config.json
Add a static endpoint named cloudserver-front, which backbeat uses to
contact the local S3 when deployed with docker swarm.
=> ft: add endpoint for backbeat w/ docker swarm

lib/api/objectCopy.js, lib/data/external/AwsClient.js, lib/data/multipleBackendGateway.js, tests/functional/aws-node-sdk/test/multipleBackend/objectCopy.js, tests/locationConfigTests.json
Do not need to re-create the source key name if we get it directly from metadata.location info :)
=> FIX: COPY-AWS: using datastore key

lib/api/completeMultipartUpload.js, lib/api/initiateMultipartUpload.js, lib/api/multiObjectDelete.js, lib/api/multipartDelete.js, lib/api/objectCopy.js, lib/api/objectDelete.js, lib/api/objectDeleteTagging.js, lib/api/objectPut.js, lib/api/objectPutACL.js, lib/api/objectPutCopyPart.js, lib/api/objectPutPart.js, lib/api/objectPutTagging.js, lib/utapi/utilities.js
Provide pushMetric with objects on the methods with storage side effects
The purpose of this PR is to permit other services accessing the same data set to keep their states consistent
=> provide pushMetric with objects

tests/functional/aws-node-sdk/test/multipleBackend/delete/delete.js, tests/functional/aws-node-sdk/test/multipleBackend/get/get.js
Adds tests for the get and delete APIs when bucketMatch = false, which was handled but not tested.
=> ft: add tests for bucketMatch false

lib/Config.js, lib/api/bucketPut.js, lib/server.js, tests/unit/api/bucketPut.js
This allows changing REST endpoint to location constraint mappings on the fly, without restarting processes, by calling `Config.setRestEndpoints()`.
=> FT: Make REST endpoint mapping dynamic

conf/authdata.json, lib/auth/in_memory/builder.js, tests/functional/aws-node-sdk/lib/json/mem_credentials.json, tests/functional/aws-node-sdk/test/bucket/put.js, tests/functional/aws-node-sdk/test/object/multiObjectDelete.js, tests/functional/raw-node/test/routes/routeBackbeat.js
Use proper ARNs for accounts, remove account users which is now unsupported.
This change will be necessary for the example file to be parsed correctly when https://github.com/scality/Arsenal/pull/346 is merged, but can be merged before since it will still be parsed correctly by the existing code in arsenal.
=> rf: update auth config example file

lib/api/apiUtils/object/getReplicationInfo.js, tests/functional/aws-node-sdk/test/bucket/putBucketReplication.js, tests/unit/api/objectReplicationMD.js
Depends on https://github.com/scality/Arsenal/pull/347.
* Add the `storageType` field to the `replicationInfo` field of an object's metadata.
* If the given `storageClass` of a replication configuration rule matches a location in the locationConfig.json, we set the `storageType` to the value of `type` (for example, 'aws_s3') that is included in the given location constraint.
* The definition of a valid `storageClass` is expanded to include values that exist in the locationConfig.json.
=> FT: Add storageType to replicationInfo

docs/CLIENTS.rst
Boto3's client is just a small part of the Boto3 library. With the
current implementation, it will return a dict of the S3 item. With this
one, it will use the boto3 mapping feature as well and will return an object
instead of a dict.
=> DOC: Change Boto3 usage to use boto3 mapping feature

lib/routes/routeBackbeat.js
Adds route for replication of single-part objects to AWS.
Forthcoming replication operation support:
* MPU objects
* Metadata-only operations (zero-byte objects, putting object ACLs, etc.)
* Object deletion
=> FT: Add replication to AWS backbeat route

tests/functional/aws-node-sdk/test/multipleBackend/delete/deleteAwsVersioning.js, tests/multipleBackend/multipartUpload.js, tests/multipleBackend/objectPutCopyPart.js, tests/multipleBackend/objectPutPart.js
Seems some of the delete aws backend tests are flaky when making direct calls to AWS, like we are getting out-of-date data. I added a timeout.
=> fix: add timeout for aws get flakiness

lib/api/objectCopy.js, lib/data/external/utils.js, lib/data/multipleBackendGateway.js, lib/data/wrapper.js, lib/kms/utilities.js, tests/functional/aws-node-sdk/lib/utility/createEncryptedBucket.js, tests/functional/aws-node-sdk/test/multipleBackend/objectCopy/azureObjectCopy.js, tests/functional/aws-node-sdk/test/multipleBackend/objectCopy/objectCopy.js, tests/functional/aws-node-sdk/test/multipleBackend/utils.js, tests/locationConfigTests.json, tests/unit/testConfigs/configTest.js
On object copy/copy part we should be copying to the data location of the destination bucket unless the user specifies REPLACE and uses the `x-amz-meta-scal-location-constraint` header.
=> S3C-1018 FIX: copy with locationConstraint

lib/Config.js, lib/api/objectCopy.js, lib/data/external/AwsClient.js, lib/data/external/AzureClient.js, lib/data/external/utils.js, lib/data/multipleBackendGateway.js, lib/data/wrapper.js, tests/functional/aws-node-sdk/test/multipleBackend/mpuComplete/mpuAwsVersioning.js, tests/functional/aws-node-sdk/test/multipleBackend/objectCopy/objectCopy.js, tests/functional/aws-node-sdk/test/multipleBackend/objectPutCopyPart/objectPutCopyPartAzure.js, tests/unit/testConfigs/configTest.js
We need to exclude certain scenarios from using AWS/Azure server-side copy (for copy object and copy part) due to encryption.
Server side copy should only be allowed:
1) if source object and destination object are both on aws or both on azure.
2) if azure to azure, must be the same storage account
3) if the source bucket is not an encrypted bucket and the destination bucket is not an encrypted bucket (unless the copy is all within the same bucket).
Also, we should make sure we are sending the sse header to aws if the destination location has SSE set to true in the locationConfig.
=> S3C-1003 FX: COPY External backends encryption

lib/api/objectGet.js
We're crashing because we're sending utapi client a string for content-length instead of an integer when we get the content-length from an external backend.  We should be parseInt'ing the content-length before we send to utapi --
```{"name":"S3","clientIP":"::ffff:172.17.0.3","clientPort":34537,"httpMethod":"GET","httpURL":"/buckettestmultiplebackendmpuawsversioning/somekey-1509312283466","time":1509312286523,"req_id":"088c852e6e4e8c7e1570","level":"info","message":"received request","hostname":"box27","pid":360}
responseMetaHeaders in objectGet!! { 'x-amz-website-redirect-location': '',
'x-amz-meta-scal-location-constraint': 'awsbackend',
'x-amz-version-id': undefined,
'Content-Length': '10485760',
ETag: '"f65590340fd7a9f7c0643548071050c7-2"',
'Last-Modified': 'Sun, 29 Oct 2017 21:24:46 …
```
=> FX: Sending utapi client string for content-length instead of int

tests/functional/aws-node-sdk/test/multipleBackend/delete/deleteAwsVersioning.js, tests/functional/aws-node-sdk/test/multipleBackend/mpuComplete/mpuAwsVersioning.js, tests/functional/aws-node-sdk/test/multipleBackend/objectTagging/taggingAwsVersioning-delete.js, tests/functional/aws-node-sdk/test/multipleBackend/objectTagging/taggingAwsVersioning-putget.js, tests/functional/aws-node-sdk/test/multipleBackend/utils.js
Increasing the wait and mocha timeouts for some tests that seem like they are still flaky on ci runs.
=> chore: increase timeouts for flaky aws versioning tests

lib/metadata/bucketfile/backend.js, tests/unit/metadata/bucketfile/backend.js
Prevent S3 unit tests from trying to access a local dmd which is not
running, by adding an option to BucketFileInterface constructor not to
attempt to open the database.
This is only for unit tests that use mocking with BucketFileInterface
and should be limited to this use.
=> bf: fix possible timeout in unit tests

lib/Config.js
When defining replication endpoints using an external backend during deployment, we want to support an optional list of servers when the `type` is a key in the `externalBackends` constant. As specified here: https://github.com/scality/Federation/blob/master/env/client-template/group_vars/all#L400.
=> FIX: replicationEndpoints config with multiplebackend

tests/functional/aws-node-sdk/test/support/awsConfig.js, tests/multipleBackend/multipartUpload.js
We relied on having a `credentialsProfile` for multiple backend tests but ended up using the `credentials` config option in the Integration set-up. We may as well support both options to get the right AWS credentials for our aws multiple backend tests.
=> fix: use credentials for getRealAwsConfig if fit

lib/routes/routeBackbeat.js, lib/utilities/collectResponseHeaders.js
Include replicated object versionId in user MD.
* When an object is replicated to an external
backend, include the replicated object's version
ID in the source object's user metadata.
* Remove 'scal-location-constraint' from
destination object's user MD as it is uneeded.
=> RF: Include replicated object versionId in user MD

lib/api/multiObjectDelete.js, tests/functional/aws-node-sdk/test/object/multiObjectDelete.js
Forward from rel/6.3 to rel/6.4
Adds a check for empty case in multiObjectDelete.
=> Forward rel/6.3 to rel/6.4

lib/data/external/AzureClient.js, lib/data/external/utils.js, lib/data/multipleBackendGateway.js, lib/data/wrapper.js, lib/utilities/healthcheckHandler.js, tests/functional/aws-node-sdk/test/multipleBackend/delete/deleteAzure.js, tests/functional/aws-node-sdk/test/multipleBackend/get/getAzure.js, tests/functional/aws-node-sdk/test/multipleBackend/initMPU/initMPUAzure.js, tests/functional/aws-node-sdk/test/multipleBackend/listParts/azureListParts.js, tests/functional/aws-node-sdk/test/multipleBackend/mpuAbort/azureAbortMPU.js, tests/functional/aws-node-sdk/test/multipleBackend/mpuComplete/azureCompleteMPU.js, tests/functional/aws-node-sdk/test/multipleBackend/mpuParts/azurePutPart.js, tests/functional/aws-node-sdk/test/multipleBackend/objectCopy/azureObjectCopy.js, tests/functional/aws-node-sdk/test/multipleBackend/objectTagging/objectTagging.js, tests/functional/aws-node-sdk/test/multipleBackend/put/putAzure.js, tests/functional/aws-node-sdk/test/multipleBackend/utils.js, tests/locationConfig/locationConfigTests.json, tests/multipleBackend/backendHealthcheckResponse.js, tests/multipleBackend/multipartUpload.js, tests/unit/utils/multipleBackendGateway.js
Add flight check during start-up option to client check. If a flight check, behavior is:
*  - return an error to halt start-up if there is any error in the client check
*  - check all external backend locations (instead of just one random location per external backend)
*  - create a container for an Azure location if one is missing
=>  rf: create azure container if flightCheckOnStartUp

tests/functional/aws-node-sdk/test/multipleBackend/delete/deleteAwsVersioning.js, tests/functional/aws-node-sdk/test/multipleBackend/objectTagging/objectTagging.js, tests/functional/aws-node-sdk/test/multipleBackend/put/put.js, tests/functional/aws-node-sdk/test/multipleBackend/utils.js
We tried to reduce the length of end to end runs before by skipping timeouts on first attempts to get data from AWS, but some thrown errors were not getting caught because try-catch scopes do not extend to code inside an asynchronous function's callback.
Refactored so we only use try-catch when we are nesting the statements which may throw errors we expect to be caught immediately within.
=> fix: try-catch should catch getAws thrown errors

lib/api/multiObjectDelete.js, tests/functional/aws-node-sdk/test/object/multiObjectDelete.js
Forward from rel/6.4 to rel/7.0
Adds a check for empty case in multiObjectDelete.
=> Forward rel/6.4 to rel/7.0

lib/Config.js, lib/data/locationConstraintParser.js
This commit adds support for a HTTP ONLY proxy for AWS client
used in AWS location constraint/backend setup.
=> ft: support http proxy for AWS backend

lib/api/bucketPutVersioning.js, lib/api/initiateMultipartUpload.js, tests/functional/aws-node-sdk/test/multipleBackend/put/putAzure.js
For buckets put to backend locations that do not support versioning (Azure atm), we should return a NotImplemented error if the user tries to put versioning on the bucket.
=> fix: error on versioning put to azure loc bucket

lib/data/external/AwsClient.js, lib/data/external/AzureClient.js, lib/data/external/utils.js, lib/data/multipleBackendGateway.js, lib/data/wrapper.js, tests/functional/aws-node-sdk/test/multipleBackend/objectCopy/azureObjectCopy.js, tests/functional/aws-node-sdk/test/multipleBackend/objectCopy/objectCopy.js, tests/functional/aws-node-sdk/test/multipleBackend/put/putAzure.js
- When copying to Azure we want to keep metadata up to date on the Azure side.
- Put and copying to Azure we want to trim `x-amz-meta`prefix from metadata header keys.
=> FIX: S3C-1087 put and copy metadata for external backends

lib/api/bucketGet.js, lib/metadata/in_memory/backend.js, tests/functional/aws-node-sdk/test/versioning/listObjectVersions.js
Depends on https://github.com/scality/Integration/pull/608
Some versioning clean-up fixes: we were returning an unencoded version id marker in list versions (if a version id marker was provided in the first place) and not returning InvalidArgument if an invalid version ID is provided.
=> fix: validate & re-encode version id marker [S3C-368]

constants.js, lib/data/multipleBackendGateway.js, lib/data/wrapper.js, tests/unit/api/objectCopy.js, tests/unit/api/objectPut.js
handle null parts on sparse objects
Null parts are parts with null keys which are generated by the NFS server when growing a file with truncate
* scality/scality-nfsd#103
* scality/Arsenal#377
* scality/Integration#601
=> FT: S3C-1065: sparse objects

lib/utilities/retrieveData.js, tests/unit/utils/responseStreamData.js
This fixes the leakage of sockets in CLOSE_WAIT state by closing the streams and
destroying the sockets when the client has abruptly closed the connection.
Depends on https://github.com/scality/sproxydclient/pull/132
=> bf: close/end readable/response streams on errors

lib/api/bucketPut.js, tests/functional/aws-node-sdk/test/bucket/put.js
This used to be protected by virtue of having capitalized letters but now that it is permitted in arsenal, protect here.
=> FT: Protect reserved bucketname

tests/functional/aws-node-sdk/test/multipleBackend/utils.js
Node sdk right now apparently does not check that body size is what was expected. I spent some time trying to figure out why we had an etag mismatch on a test with the aws backend --
http://ci.ironmann.io/gh/scality/S3/9975
After looking through the logs, it's clear the connection with aws dropped before all of the data was retrieved but this was not apparent from the test.  This should help in the future.
=> TEST: Add content length check on get

lib/server.js, lib/utilities/retrieveData.js
Harden handling of events at different stages, so that we close sockets fds in
all situations, especially when the S3 client aborts the connection while we
are processing a GET request. This used to generate a FD leak, leading to
unread tcp buffers and memory leak (observed in netstat output).
=> S3C-1026: tcp leak

config.json, docker-entrypoint.sh, lib/metadata/mongoclient/backend.js
=> Improved logging and Replica set compatibility

lib/data/external/GCP/GcpService.js, lib/data/external/GCP/gcp-2017-11-01.api.json, lib/data/external/GcpClient.js, lib/data/external/utils.js, lib/data/multipleBackendGateway.js, tests/functional/raw-node/test/GCP/README.MD, tests/functional/raw-node/test/GCP/bucket/get.js, tests/functional/raw-node/test/GCP/bucket/getVersioning.js, tests/functional/raw-node/test/GCP/bucket/head.js, tests/functional/raw-node/test/GCP/bucket/putVersioning.js, tests/functional/raw-node/utils/gcpUtils.js, tests/locationConfig/locationConfigTests.json
Implements the APIs to enable backend healthcheck of GCP storages buckets
For client backend healthcheck.
Reference Docs:
HEAD API: https://cloud.google.com/storage/docs/xml-api/head-bucket
GET API: https://cloud.google.com/storage/docs/xml-api/get-bucket-list
PUT Versioning: https://cloud.google.com/storage/docs/xml-api/put-bucket-versioning
GET Versioning: https://cloud.google.com/storage/docs/xml-api/get-bucket-versioning
=> S3C-1115 FT: Adds GCP Backend healthcheck

tests/functional/aws-node-sdk/test/multipleBackend/listParts/azureListParts.js
Why is this change required? What problem does it solve?
Please use the following link syntaxes #600 to reference issues in the
current repository
New tests added or existing tests modified to cover all changes
In order to contribute to the project, you must sign your work
https://github.com/scality/Guidelines/blob/master/CONTRIBUTING.md#sign-your-work
Thank you again for contributing! We will try to test and integrate the change
as soon as we can.
=> Fwdport 7.2 to rel/7.4 (formerly master)

lib/data/external/GcpClient.js
Removes one layer of nesting that leads to errors not being detected.
=> [FIX] GCP Healthcheck

tests.bash
=> Update mongo version in tests

lib/Config.js, tests.bash, tests/locationConfig/locationConfigTests.json
Fixes the bug where it doesn't handle retrieving environment variables
with '\n', newline, correctly: '\n' will be retrieved as '\\\n'.
Changes the method for supplying the service credentials for the JSON api (from keyfile to email/key pair)
Adds gcpbackend2's own mpu bucket and overflow bucket.
=> FX: GCP Credentials

lib/api/apiUtils/object/createAndStoreObject.js, lib/api/bucketPutVersioning.js, lib/api/initiateMultipartUpload.js, lib/api/objectCopy.js, lib/data/external/GcpClient.js
Removes GCP versioning check on buckets.
Adds to `externalVersioningErrorMessage` to cover GCP.
The `externalVersioningErrorMessage` is currently hard coded.
=> Removes versioning check as part of GCP backend healthcheck

lib/data/external/GCP/GcpApis/copyObject.js
Bug: copyObject result parses all elements as strings
Fix: parse result elements with correct type.
=> Fix GCP CopyObject Result Parse

lib/utilities/reportHandler.js, tests/functional/report/checkRoutes.js
Only send `overlayVersion` for now to avoid sending unwanted items.
=> Fix: limit exported config items

circle.yml, constants.js, lib/Config.js, lib/api/objectPutPart.js, lib/data/external/GCP/GcpApis/listParts.js, lib/data/external/GCP/GcpApis/uploadPart.js, lib/data/external/GCP/GcpApis/uploadPartCopy.js, lib/data/external/GCP/GcpUtils.js, lib/data/external/GcpClient.js, lib/data/multipleBackendGateway.js, lib/data/wrapper.js, tests/functional/aws-node-sdk/test/multipleBackend/initMPU/initMPUGcp.js, tests/functional/aws-node-sdk/test/multipleBackend/listParts/listPartsGcp.js, tests/functional/aws-node-sdk/test/multipleBackend/mpuAbort/abortMPUGcp.js, tests/functional/aws-node-sdk/test/multipleBackend/mpuComplete/completeMPUGcp.js, tests/functional/aws-node-sdk/test/multipleBackend/mpuParts/putPartGcp.js, tests/functional/aws-node-sdk/test/multipleBackend/objectPutCopyPart/objectPutCopyPartGcp.js, tests/functional/aws-node-sdk/test/multipleBackend/utils.js, tests/unit/utils/gcpMpuHelpers.js, tests/unit/utils/gcpTaggingHelpers.js
=> Ft/s3 c 1179/gcp s3 mpu

lib/data/external/GCP/GcpManagedUpload.js
the missing err argument will cause S3 to crash as the logger will attempt to read the `message` property from an `undefined`.
fix: passes err to be returned in callback
=> fx: add err

config.json, docker-entrypoint.sh, lib/Config.js, lib/utilities/reportHandler.js
This is the first effort to use forthcoming Backbeat routes for retrieving metrics (to be added by https://github.com/scality/backbeat/pull/200). The next step is to extract metrics accumulation code and move it to Arsenal so that we can avoid making an HTTP request to Backbeat.
=> FT: Add CRR statistics for Orbit

lib/data/external/GCP/GcpSigner.js, package.json
Includes S3 PR https://github.com/scality/S3/pull/1167
=> fx: use core querysting instead of qs module

tests/functional/aws-node-sdk/test/multipleBackend/delete/deleteGcp.js, tests/functional/aws-node-sdk/test/multipleBackend/get/getGcp.js, tests/functional/aws-node-sdk/test/multipleBackend/put/putGcp.js
Adds GCP backend functional tests for PUT/GET/DELETE methods
=> FT S3C-1115: GCP S3 Functional Tests

docker-entrypoint.sh
Matches the `MONGODB_DATABASE` variable that backbeat's docker entrypoint handles.
=> Make mongodb database configurable

lib/data/external/AwsClient.js, lib/data/external/GcpClient.js, tests/unit/DummyService.js, tests/unit/multipleBackend/ExternalBackendClient.js
externally handled MPU will return ContentLength as string, and this is failing the utapi push metrics assertion, in which requires ContentLength must be an integer
=> bf: parse content length to int

lib/Config.js, tests.bash, tests/functional/report/checkRoutes.js
These changes should fix our tests.
This check was not skipping tests: https://github.com/scality/S3/blob/master/tests/functional/aws-node-sdk/test/multipleBackend/utils.js#L40
=> FX: functional tests

lib/Config.js, lib/data/locationConstraintParser.js, tests/locationConfig/locationConfigTests.json, tests/unit/testConfigs/locConstraintAssert.js
This feature allows setting pathStyle requests option for location constraints so that
it can be relaxed for non-AWS S3 backends (for example S3 Connector)
=> ft: provide pathStyle option to support S3C

circle.yml, config.json, tests.bash
Fixes the problem where the functional tests with mongo would not run correctly causing CircleCi to falsely pass. 
Uploaded a new ci-mongo docker image based off Federation and that self initializes to a single node replica set for compatibility.
=> Fix mongo tests

lib/utilities/collectResponseHeaders.js, tests/functional/aws-node-sdk/test/object/get.js, tests/functional/aws-node-sdk/test/object/objectHead.js, tests/unit/utils/collectResponseHeaders.js
Compatibility fix with AWS S3. The WebsiteRedirectLocation will not be included in the get object or head responses if it was not set on the object.
AWS S3 output:
```json
{
"AcceptRanges": "bytes",
"ContentType": "binary/octet-stream",
"LastModified": "Tue, 10 Apr 2018 05:42:07 GMT",
"ContentLength": 0,
"ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
"Metadata": {}
}
```
Cloudserver previous output:
```json
{
"LastModified": "Tue, 10 Apr 2018 05:46:03 GMT",
"ContentLength": 0,
"ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
"WebsiteRedirectLocation": "",
"Metadata": {}
}
```
=> FIX: WebsiteRedirectLocation header response

.github/ISSUE_TEMPLATE.md
Following conversations with Jono Bacon, it was highlighted that we should insist on redirecting people to the forum on the issue submission form. This pull request attempts to make a stronger statement than before on this matter.
=> RF: ZNC-26: Issue Template to highlight Discourse

lib/metadata/bucketclient/backend.js
As discussed in S3C-1412, it is necessary for S3 to interpret Bucketd health
status in order to provide more flexibility (relatively to the health check
mechanism) than failing due to a light partial unavailability of the platform.
This is done in the bucketclient backend's healthcheck method, in order to
comply with all the other backends.
Fixes S3C-1412
Note:
I still need to check whether tests exist for the modified piece of code (Doubtful given that it relies on an external service, which isn't supposed to be used in S3 unit/func testing), and update them if any is present.
=> S3C-1412: Interpret healthCheck Status from Bucketd

lib/data/external/AwsClient.js, lib/routes/routeBackbeat.js, tests/multipleBackend/multipartUpload.js
When putting an MPU object using an AWS location constraint, any user metadata is included twice.
Example response from a headObject request:
```
{
"AcceptRanges": "bytes",
"ContentType": "application/octet-stream",
"LastModified": "Tue, 20 Mar 2018 22:11:39 GMT",
"ContentLength": 10485762,
"VersionId": "rbu8wlrAt7Jd_HUV9VctoSp3mIjQtg4M",
"ETag": "\"794898c411e565027c2c3ba534b00e2d-2\"",
"Metadata": {
"x-amz-meta-customkey": "customValue",
"customkey": "customValue"
}
}
```
=> FIX: Do not include untrimmed headers

lib/data/external/GCP/GcpApis/mpuHelper.js
Properties (e.g. ContentType) on the source MPU do not end up as values of the final object when doing CRR to GCP.
=> bf: ZENKO-275 CRR to GCP MPU properties

lib/Config.js, lib/utapi/utapi.js, lib/utapi/utapiReplay.js, lib/utapi/utilities.js
Depends on  https://github.com/scality/Federation/pull/1494.
=> rf: S3C-1399 Update Redis configuration

lib/api/apiUtils/bucket/parseLikeExpression.js, lib/api/apiUtils/bucket/parseWhere.js, tests/functional/aws-node-sdk/test/mdSearch/basicSearch.js, tests/functional/aws-node-sdk/test/mdSearch/utils/helpers.js, tests/unit/api/parseLikeExpression.js
Original code will evaluate regex in `/pattern/` syntax incorrectly
Adds parser to have MD search recognize if a regex is in `/pattern/` syntax or
a simple string
=> bf: ZENKO-250 correctly evaluate regex pattern

lib/data/external/AzureClient.js
This fixes the issue in Federation deployments where Azure backend request would default to localhost when using a proxy.
=> bf: ZENKO-332 fix Azure proxy localhost req

lib/utilities/reportHandler.js
A new “redis” configuration item that can not be set easily in containers while one already exists called localCache which is already configurable
=> fix: use existing localCache redis configuration

lib/api/apiUtils/authorization/aclChecks.js, lib/api/apiUtils/bucket/bucketCreation.js, tests/unit/api/bucketACLauth.js
Add support for service account 'service-lifecycle' in addition to
existing 'service-replication'. ACL checks are shunted in both cases,
we may implement more fine-grained access control later.
=> ft: ZENKO-404 lifecycle service account
